.class public LX/7Hj;
.super Ljava/lang/Object;
.source ""


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:J

.field public A0C:LX/7yr;

.field public A0D:LX/7yr;

.field public A0E:LX/7yq;

.field public A0F:LX/7yu;

.field public A0G:LX/7z8;

.field public A0H:LX/7yw;

.field public A0I:LX/7yo;

.field public A0J:LX/7yt;

.field public A0K:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0L:LX/7z1;

.field public A0M:LX/7ys;

.field public A0N:LX/7yn;

.field public A0O:LX/7z3;

.field public A0P:LX/7z3;

.field public A0Q:LX/7yp;

.field public A0R:Ljava/lang/String;

.field public A0S:Ljava/util/HashMap;

.field public A0T:Ljava/util/Map;

.field public A0U:Ljava/util/Set;

.field public A0V:Ljava/util/Set;

.field public A0W:Ljava/util/Set;

.field public A0X:Ljava/util/Set;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Z

.field public A0b:Z

.field public A0c:Z

.field public A0d:Z

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z


# direct methods
.method public constructor <init>()V
    .locals 7

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v3, 0x0

    iput-boolean v3, p0, LX/7Hj;->A0h:Z

    sget-object v0, LX/7z9;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/7Hj;->A0K:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    const/4 v1, 0x1

    iput-boolean v3, p0, LX/7Hj;->A0a:Z

    const/16 v2, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/7Hj;->A0R:Ljava/lang/String;

    const/16 v6, 0xfa

    iput-boolean v1, p0, LX/7Hj;->A0g:Z

    new-instance v0, LX/7IR;

    invoke-direct {v0}, LX/7IR;-><init>()V

    iget-boolean v1, v0, LX/7IR;->A00:Z

    new-instance v0, LX/7yt;

    invoke-direct {v0, v1}, LX/7yt;-><init>(Z)V

    iput-object v0, p0, LX/7Hj;->A0J:LX/7yt;

    const/16 v1, 0x3e8

    const/16 v5, 0x1f4

    new-instance v0, LX/7z3;

    invoke-direct {v0, v5, v2}, LX/7z3;-><init>(II)V

    iput-object v0, p0, LX/7Hj;->A0O:LX/7z3;

    new-instance v0, LX/7z3;

    invoke-direct {v0, v3, v3}, LX/7z3;-><init>(II)V

    iput-object v0, p0, LX/7Hj;->A0P:LX/7z3;

    new-instance v0, LX/7z1;

    invoke-direct {v0}, LX/7z1;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0L:LX/7z1;

    new-instance v0, LX/6z7;

    invoke-direct {v0}, LX/6z7;-><init>()V

    new-instance v0, LX/7yw;

    invoke-direct {v0}, LX/7yw;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0H:LX/7yw;

    sget-object v0, LX/7z8;->A00:LX/7z8;

    iput-object v0, p0, LX/7Hj;->A0G:LX/7z8;

    new-instance v0, LX/6yz;

    invoke-direct {v0}, LX/6yz;-><init>()V

    new-instance v0, LX/7yu;

    invoke-direct {v0}, LX/7yu;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0F:LX/7yu;

    new-instance v0, LX/6yy;

    invoke-direct {v0}, LX/6yy;-><init>()V

    new-instance v0, LX/7yq;

    invoke-direct {v0}, LX/7yq;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0E:LX/7yq;

    new-instance v0, LX/6z8;

    invoke-direct {v0}, LX/6z8;-><init>()V

    new-instance v0, LX/7yo;

    invoke-direct {v0}, LX/7yo;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0I:LX/7yo;

    new-instance v0, LX/6zA;

    invoke-direct {v0}, LX/6zA;-><init>()V

    new-instance v0, LX/7yp;

    invoke-direct {v0}, LX/7yp;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0Q:LX/7yp;

    new-instance v0, LX/7yn;

    invoke-direct {v0}, LX/7yn;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0N:LX/7yn;

    new-instance v4, LX/7Ez;

    invoke-direct {v4}, LX/7Ez;-><init>()V

    const v0, 0x186a0

    iput v0, v4, LX/7Ez;->A00:I

    iput v1, v4, LX/7Ez;->A03:I

    iput v5, v4, LX/7Ez;->A02:I

    iput v6, v4, LX/7Ez;->A01:I

    new-instance v0, LX/7yr;

    invoke-direct {v0, v4}, LX/7yr;-><init>(LX/7Ez;)V

    iput-object v0, p0, LX/7Hj;->A0C:LX/7yr;

    new-instance v4, LX/7Ez;

    invoke-direct {v4}, LX/7Ez;-><init>()V

    iput v2, v4, LX/7Ez;->A00:I

    const v0, 0x249f0

    iput v0, v4, LX/7Ez;->A03:I

    const v0, 0x86470

    iput v0, v4, LX/7Ez;->A02:I

    const v0, 0x1e8480

    iput v0, v4, LX/7Ez;->A01:I

    new-instance v0, LX/7yr;

    invoke-direct {v0, v4}, LX/7yr;-><init>(LX/7Ez;)V

    iput-object v0, p0, LX/7Hj;->A0D:LX/7yr;

    iput-boolean v3, p0, LX/7Hj;->A0b:Z

    iput-boolean v3, p0, LX/7Hj;->A0c:Z

    const/16 v6, 0xfa0

    invoke-static {}, LX/002;->A0P()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0S:Ljava/util/HashMap;

    const-wide/16 v4, 0x0

    iput-wide v4, p0, LX/7Hj;->A0B:J

    invoke-static {}, LX/002;->A0P()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0T:Ljava/util/Map;

    const/16 v0, 0x7530

    iput v0, p0, LX/7Hj;->A04:I

    const/4 v0, -0x1

    iput v0, p0, LX/7Hj;->A0A:I

    iput v6, p0, LX/7Hj;->A03:I

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0X:Ljava/util/Set;

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0W:Ljava/util/Set;

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0Y:Ljava/util/Set;

    new-instance v0, LX/7ys;

    invoke-direct {v0}, LX/7ys;-><init>()V

    iput-object v0, p0, LX/7Hj;->A0M:LX/7ys;

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0V:Ljava/util/Set;

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0U:Ljava/util/Set;

    invoke-static {}, LX/002;->A0Q()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7Hj;->A0Z:Ljava/util/Set;

    const/16 v0, 0x28

    iput v0, p0, LX/7Hj;->A09:I

    iput v0, p0, LX/7Hj;->A08:I

    iput v3, p0, LX/7Hj;->A07:I

    iput v1, p0, LX/7Hj;->A06:I

    iput v2, p0, LX/7Hj;->A05:I

    iput v1, p0, LX/7Hj;->A00:I

    iput v1, p0, LX/7Hj;->A02:I

    const v0, 0x8000

    iput v0, p0, LX/7Hj;->A01:I

    return-void
.end method
