.class public LX/7z9;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A01:LX/7z9;

.field public static final serialVersionUID:J = -0xb6b8c66d093f82bL


# instance fields
.field public final abrMonitorEnabled:Z

.field public final abrSetting:LX/7yw;

.field public final adBreakEnahncedPrefetchDurationMs:I

.field public final adjustSpeedBottomThresholdMs:I

.field public final adjustSpeedTopThresholdMs:I

.field public final advanceSegmentOnNetworkErrors:J

.field public final aggressiveEdgeLatencyForLsbConfPercentile:I

.field public final aggressiveEdgeLatencyOverrideForLSB:J

.field public final allowImmediateLiveBufferTrim:Z

.field public final allowMultiPlayerFormatWarmup:Z

.field public final allowOutOfBoundsAccessForPDash:Z

.field public final allowOverridingPlayerWarmUpWatermark:Z

.field public final allowPredictiveAlignment:Z

.field public final allowedExtendedMinRebuffePeriodMs:I

.field public final allowedExtendedPremiumTierRebufferPeriodMs:I

.field public final allowedExtendedRebufferPeriodMs:I

.field public final alwaysPerformContentLengthUpdateFirst:Z

.field public final alwaysPrefetchInBgDefaultPriorityThread:Z

.field public final alwaysPrefetchInIdleExecutor:Z

.field public final alwaysReuseManifestFetcher:Z

.field public final appendReconfigurationDataForDrmContentFix:Z

.field public final asyncReleaseSurfaceOnMainThread:Z

.field public final attachGrootPlayerListenerWhenUsingSurfaceControl:Z

.field public final audioBufferSize:I

.field public final audioLazyLoadSetting:LX/7yo;

.field public final audioStallCountThresholdMs:I

.field public final audioTrackInitFailedFallbackApplyThreshold:I

.field public final audioVideoSyncPeriodMs:I

.field public final autogenSettings:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final av1Dav1dEnableVpsLogging:Z

.field public final av1Dav1dUseSurfaceViewSetFix:Z

.field public final av1FlushDav1dProperly:Z

.field public final av1SetBuffersDataspace:Z

.field public final av1ThrowExceptionOnNonDav1dDecoder:Z

.field public final av1ThrowExceptionOnPictureError:Z

.field public final av1UseDav1dSynchronizationFixes:Z

.field public final av1UseMemoryCleanupFixes:Z

.field public final avoidSecondPhaseOnCell:Z

.field public final avoidServiceClassLoadOnClient:Z

.field public final bandwidthEstimationSetting:LX/7yq;

.field public final bandwidthMultiplierForAggressiveEdgeLatency:F

.field public final bandwidthMultiplierToSkipPrefetchedContent:F

.field public final bgHeroServiceStatusUpdate:Z

.field public final blackscreenDetectOnce:Z

.field public final blackscreenNoSampleThresholdMs:J

.field public final blackscreenSampleIntervalMs:J

.field public final blockDRMPlaybackOnHDMI:Z

.field public final blockDRMScreenCapture:Z

.field public final blockListedHardwareDecoderMap:Ljava/util/HashMap;

.field public final broadcasterIdAllowlist:Ljava/lang/String;

.field public final bufferDecreaseTimeMs:I

.field public final bufferedCacheDataSinkSize:I

.field public final bufferedDurationBasedHttpPriorityLowerBoundMs:I

.field public final bufferedDurationBasedHttpPriorityUpperBoundMs:I

.field public final bypassGreaterThanMinRebufferWhenBeforePlay:Z

.field public final cache:LX/7yt;

.field public final callbackFirstCaughtStreamError:Z

.field public final cancelOngoingRequest:Z

.field public final cellMaxWatermarkMsConfig:LX/7yr;

.field public final changePriorityForPrefetchRequestOnPlayerStart:Z

.field public final changeThreadPriorityForPrefetch:Z

.field public final checkCachedLockedCacheSpan:Z

.field public final checkLiveSourceUri:Z

.field public final checkManifestRepresentationFormatMismatch:Z

.field public final checkPlayerStateIntervalIncreaseMs:I

.field public final checkPlayerStateMaxIntervalMs:I

.field public final checkPlayerStateMinIntervalMs:I

.field public final checkReadToEndBeforeUpdatingFinalState:Z

.field public final checkThumbnailCache:Z

.field public final chunkSourceRetryMaximum:I

.field public final cleanUpHeartbeatMessagesIfNotPlaying:Z

.field public final cleanUpHeartbeatMessagesOnPause:Z

.field public final cleanUpHeartbeatMessagesOnStall:Z

.field public final clearBufferingWhenInWarmup:Z

.field public final combineInitFirstSegment:Z

.field public final concatenatedMsPerLoadConfig:LX/7yr;

.field public final continueLoadingOnSeekbarExo2:Z

.field public final continuouslyLoadFromPreSeekLocation:Z

.field public final customizedPrefetchThreadPriority:I

.field public final customizedWABufferForPlaybackMs:I

.field public final customizedWAIndividualAllocationSize:I

.field public final customizedWARebufferMs:I

.field public final dashHighWatermarkMs:I

.field public final dashLowWatermarkMs:I

.field public final dashManifestPoolSize:I

.field public final dav1dApplyGrain:Z

.field public final dav1dMaxFrameDelay:I

.field public final dav1dThreads:I

.field public final decoderDequeueRetryTimeMs:I

.field public final decoderInitializationRetryTimeMs:I

.field public final defaultUserAgent:Ljava/lang/String;

.field public final delayWarmupRunningMs:I

.field public final depthTocheckSurfaceInvisibleParent:I

.field public final desiredBufferAcceptableErrorMs:I

.field public final disableAudioFocusInGroot:Z

.field public final disableAudioRendererOnAudioTrackInitFailed:Z

.field public final disableCapBufferSizeLocalProgressive:Z

.field public final disableIsCachedApi:Z

.field public final disableLatencyManagerOnStaticManifest:Z

.field public final disableLiveCaptioningOnPlayerInit:Z

.field public final disableLoadingRetryOnFatalError:Z

.field public final disableNetworkErrorCountInChunkSource:Z

.field public final disablePoolingForDav1dMediaCodec:Z

.field public final disablePreallocateCodecDuringStartup:Z

.field public final disableRecoverInBackground:Z

.field public final disableSecondPhasePrefetchForDataSaver:Z

.field public final disableSecondPhasePrefetchForReels:Z

.field public final disableSecondPhasePrefetchOnAppScrolling:Z

.field public final disableSkipInlineForHuddle:Z

.field public final disableSpeedAdjustmentOnBadUserExperience:Z

.field public final disableStoriesCustomizedUnstallBuffer:Z

.field public final disableTextEraLoggingOnLoadRetry:Z

.field public final disableTextRendererOn404InitSegmentLoadError:Z

.field public final disableTextRendererOn404LoadError:Z

.field public final disableTextRendererOn500InitSegmentLoadError:Z

.field public final disableTextRendererOn500LoadError:Z

.field public final disableTextTrackOnMissingTextTrack:Z

.field public final disableTigonBandwidthLogging:Z

.field public final disableUllBasedOnHoldout:Z

.field public final disableVideoTrackForInVisibleVDD:Z

.field public final dontRetry403OnExpiredUrl:Z

.field public final drmSessionStoreCapacity:I

.field public final dummyDefaultSetting:Z

.field public final dynamicDiscontinuityInitialPosMs:I

.field public final dynamicInfoSetting:LX/7yu;

.field public final earlyPreallocateCodecOnAppNotScrolling:Z

.field public final earlyPreallocateCodecOnIdle:Z

.field public final enable204SegmentRemapping:Z

.field public final enable404SegmentRemapping:Z

.field public final enable416Logging:Z

.field public final enable500R1FallbackLogging:Z

.field public final enableAV1SRShader:Z

.field public final enableActiveDrmSessionStoreRelease:Z

.field public final enableAdBreakEnhancedPrefetch:Z

.field public final enableAdditionalDecoderInitFailureMessage:Z

.field public final enableAllLongerPrefetchAds:Z

.field public final enableAlwaysCallPreallocateCodec:Z

.field public final enableAsynchronousBufferQueueing:Z

.field public final enableAudioTrackRetry:Z

.field public final enableAv1Dav1d:Z

.field public final enableAv1LibGav1:Z

.field public final enableAvc1ColorConfigParseFix:Z

.field public final enableBackgroundServicePlayerReuse:Z

.field public final enableBackwardJumpSeekKeyframeSync:Z

.field public final enableBitrateAwareAudioPrefetch:Z

.field public final enableBlackscreenDetector:Z

.field public final enableBlockListingResource:Z

.field public final enableBoostOngoingPrefetchPriorityPlay:Z

.field public final enableBoostOngoingPrefetchPriorityPrepare:Z

.field public final enableBufferAwareJumpSeek:Z

.field public enableBusySignalToFramework:Z

.field public final enableCDNDebugHeaders:Z

.field public final enableCacheBlockWithoutTimeout:Z

.field public final enableCacheLookUp:Z

.field public final enableCacheNetworkTypeIfNotSet:Z

.field public final enableCachedBandwidthEstimate:Z

.field public final enableCancelFollowupPrefetch:Z

.field public final enableCancelOngoingPrefetchPause:Z

.field public final enableCancelOngoingRequestPause:Z

.field public final enableCancelPrefetchInQueuePrepare:Z

.field public final enableCaseInsensitiveHttpResponseHeaderKey:Z

.field public final enableCheckAudioError:Z

.field public final enableClearStallOnBroadcastEnd:Z

.field public final enableClockSync:Z

.field public final enableCodecDeadlockFix:Z

.field public final enableCodecHistoryOverlayField:Z

.field public final enableCodecPreallocation:Z

.field public final enableContinueLoadingLoggingForManifest:Z

.field public final enableContinueLoadingLoggingForMedia:Z

.field public final enableCreateByteBufferFromABufferNullCheckHooks:Z

.field public final enableCustomizedDRCEffect:Z

.field public final enableCustomizedDRCForHeadset:Z

.field public final enableCustomizedPrefetchThreadPriority:Z

.field public final enableCustomizedXHEAACConfig:Z

.field public final enableDashManifestPool:Z

.field public final enableDav1dAsMediaCodecAdapter:Z

.field public final enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

.field public final enableDav1dOpenGLRendering:Z

.field public final enableDav1dOpenGLRenderingHandleAspectRatio:Z

.field public final enableDebugLogs:Z

.field public final enableDeduplicateImfEmsgAtPlayer:Z

.field public final enableDelayWarmupRunning:Z

.field public final enableDemoteOngoingPrefetchPriorityPause:Z

.field public final enableDrmProvisioningRetry:Z

.field public final enableDrmSessionStore:Z

.field public final enableDynamicCursorDistance:Z

.field public final enableDynamicDiscontinuityDistance:Z

.field public final enableDynamicMinRebufferMsController:Z

.field public enableDynamicPrefetchCacheFileSize:Z

.field public enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

.field public final enableE2ECDNTracing:Z

.field public final enableEmsgPtsAlignment:Z

.field public final enableEmsgTrackForAll:Z

.field public final enableEnsureBindService:Z

.field public final enableEvictCacheOnExoplayerErrors:Z

.field public final enableEvictPlayerOnAudioTrackInitFailed:Z

.field public final enableExcessiveNumUriRedirectLogging:Z

.field public final enableExplicitTextDataSourceCreation:Z

.field public final enableFBLiteHttpDataSource:Z

.field public final enableFallbackToMainProcess:Z

.field public final enableFillBufferHooks:Z

.field public final enableFillFreeBufferCheckNodeHooks:Z

.field public final enableFirstWarmUpRequestOnScreen:Z

.field public final enableFixForOnPreparingCallback:Z

.field public final enableFixRemovePlayerViewFromParent:Z

.field public final enableFixTrackIndexOOB:Z

.field public final enableFrameBasedLogging:Z

.field public final enableFreeNodeHooks:Z

.field public final enableGlobalNetworkMonitor:Z

.field public final enableGlobalStallMonitor:Z

.field public final enableGrootAlwaysSendPlayStarted:Z

.field public final enableHttpPriorityForPrefetch:Z

.field public final enableHttpPriorityForStreaming:Z

.field public final enableHybridCacheForPrefetch:Z

.field public final enableIgHttpDataSource:Z

.field public final enableInstreamAdsEmsgLog:Z

.field public final enableIsTextAdaptationSetNotFoundLogging:Z

.field public final enableJumpTrackFallingBehind:Z

.field public final enableKillProcessBeforeRebind:Z

.field public final enableKillVideoProcessForAudioTrackInitFailed:Z

.field public final enableKillVideoProcessForIllegalStateException:Z

.field public final enableLastPlaybackSpeedCacheUpdate:Z

.field public final enableLatencyManagerRateLimiting:Z

.field public final enableLatencyPlaybackSpeed:Z

.field public final enableLazyAudioLoadForProgressive:Z

.field public final enableLiveBWEstimation:Z

.field public final enableLiveBroadcastErrorUI:Z

.field public final enableLiveBufferMeter:Z

.field public final enableLiveJumpByTrimBuffer:Z

.field public final enableLiveLatencyManager:Z

.field public final enableLiveOneTimeLoadingJump:Z

.field public final enableLiveTierSpecificBufferSetting:Z

.field public final enableLiveTierSpecificRebuffer:Z

.field public final enableLoadErrorHandlingPolicy:Z

.field public final enableLoaderRetryLoggingForManifest:Z

.field public final enableLoaderRetryLoggingForMedia:Z

.field public final enableLocalSocketProxy:Z

.field public final enableLogExceptionMessageOnError:Z

.field public final enableLogSemiCachedEvents:Z

.field public final enableLoggingEmptyOrNullVideoId:Z

.field public final enableLongCacheKeyForContentLength:Z

.field public final enableLowLatencyDecoding:Z

.field public final enableLowLatencyDecodingOverrideSDKGating:Z

.field public final enableMP3Extractor:Z

.field public final enableMediaCodecPoolingForLiveAudio:Z

.field public final enableMediaCodecPoolingForLiveVideo:Z

.field public final enableMediaCodecPoolingForProgressiveAudio:Z

.field public final enableMediaCodecPoolingForProgressiveVideo:Z

.field public final enableMediaCodecPoolingForVodAudio:Z

.field public final enableMediaCodecPoolingForVodVideo:Z

.field public final enableMediaCodecReuseOptimizeLock:Z

.field public final enableMediaCodecReuseOptimizeRelease:Z

.field public final enableMediaSessionControls:Z

.field public final enableMemoryAwareBufferSizeUsingRed:Z

.field public final enableMemoryAwareBufferSizeUsingYellow:Z

.field public final enableMixeCodecManifestLogging:Z

.field public final enableMixeCodecManifestVideoCodecSwitchedLogging:Z

.field public final enableMixedCodecManifestSupport:Z

.field public final enableMp3Mp4ExtractorLogic:Z

.field public final enableMp4MultiTrafBoxesFix:Z

.field public final enableMpdFilteringUtils:Z

.field public final enableNeedCenteringIndependentlyGroot:Z

.field public final enableOffloadInitHeroService:Z

.field public final enableOffloadingIPC:Z

.field public final enableOnMessageReceivedHooks:Z

.field public final enableOnOMXEmptyBufferDoneHooks:Z

.field public final enableOneSemanticsLoaderRetry:Z

.field public final enableOpenGLSurfaceSizeUpdateFix:Z

.field public final enableOverrideBufferWatermark:Z

.field public final enableOverrideEndPosition:Z

.field public final enablePCMBufferListener:Z

.field public final enablePIDForHuddle:Z

.field public final enablePauseNow:Z

.field public final enablePlayerActionStateLoggingInFlytrap:Z

.field public final enablePreSeekToApi:Z

.field public final enablePredictedUrlTracing:Z

.field public final enablePrefetchCancelCallback:Z

.field public final enableProgressiveFallbackWhenNoRepresentations:Z

.field public final enableProgressivePrefetchWhenNoRepresentations:Z

.field public final enableQuickDashPlayback:Z

.field public final enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

.field public final enableRebootDeviceErrorUIForCodecInitFailed:Z

.field public final enableRebootDeviceErrorUIForIllegalStateException:Z

.field public final enableReduceRetryBeforePlay:Z

.field public final enableRequestAnalyticsTagsHeaderLogging:Z

.field public final enableRequestEtdHeader:Z

.field public final enableRetryErrorLoggingInCancel:Z

.field public final enableRetryOnConnection:Z

.field public final enableRetryWarmup:Z

.field public final enableSaturation:Z

.field public final enableSeamlessAudioCodecAdaptation:Z

.field public final enableSecondPhaseAlignment:Z

.field public final enableSecondPhasePrefetch:Z

.field public final enableSecondPhasePrefetchWebm:Z

.field public final enableSecondaryChannelLoggingForLite:Z

.field public final enableSegmentIndexCheckForPrefetchBytes:Z

.field public final enableSendCommandHooks:Z

.field public final enableServerSideAbr:Z

.field public final enableServerSideForwardBwe:Z

.field public final enableServerSideForwardTracing:Z

.field public final enableSpatialOpusRendererExo2:Z

.field public final enableSsBweHeaderForLive:Z

.field public final enableStopWarmupSchedulerEmpty:Z

.field public final enableStreamLatencyToggleOverride:Z

.field public final enableSuspensionAfterBroadcasterStall:Z

.field public final enableSynchronizeCodecInteractionsWithQueueing:Z

.field public final enableSystrace:Z

.field public final enableTextTrackWithKnownLanguage:Z

.field public final enableTransferListenerCallbackPerfFix:Z

.field public final enableUnexpectedExoExceptionLogging:Z

.field public final enableUnifiedGrootErrorHandling:Z

.field public final enableUpdateProgressiveContentLengthFromCache:Z

.field public final enableUsingASRCaptions:Z

.field public final enableVideoDebugEventLogging:Z

.field public final enableVideoHybridCache:Z

.field public final enableVideoMemoryCache:Z

.field public final enableVideoPlayerServerSideBweAnnotations:Z

.field public final enableVideoPositionLoggingInCompleteEvent:Z

.field public final enableVodContentLengthLogging:Z

.field public final enableVodDrmPrefetch:Z

.field public final enableVodPausedLoading:Z

.field public final enableVp9CodecPreallocation:Z

.field public final enableVrlQplLoggingEvents:Z

.field public final enableWarmCodec:Z

.field public final enableWarmUpRequestOffscreen:Z

.field public final enableWarmupProcessPeriodically:Z

.field public final enableWarmupScheduler:Z

.field public final enableWarmupSchedulerRightAway:Z

.field public final enableWarmupSkipScheduler:Z

.field public final enableWifiLockManager:Z

.field public final enableWifiLongerPrefetchAds:Z

.field public final enabledViewManagementInGroot:Z

.field public final enforceSizeLimitOnSecondPhasePrefetch:Z

.field public final enhanceParseException:Z

.field public final errorRecoveryAttemptRepeatCountFlushThreshold:I

.field public final exceedRendererCapabilitiesIfAllFilteredOut:Z

.field public final excessiveUriRedirectLoggingLimit:I

.field public final exo2ReuseManifestAfterInitialParse:Z

.field public final exo2Vp9UseSurfaceRenderer:Z

.field public final exoPlayerUpgrade218verifyApplicationThread:Z

.field public final expBackOffSpeedUp:F

.field public final expBackoffInRetryBaseDelay:I

.field public final extendedApiTierLiveRebufferThresholdMs:I

.field public final extendedLiveRebufferThresholdMs:I

.field public final extendedMinRebufferThresholdMs:I

.field public final extendedPremiumTierLiveRebufferThresholdMs:I

.field public final fallbackToFirstSegment:Z

.field public final fbstoriesMinBufferMsConfig:LX/7yr;

.field public final fbstoriesMinRebufferMsConfig:LX/7yr;

.field public final fetchCacheSourceHttpConnectTimeoutMsConfig:LX/7yr;

.field public final fetchHttpReadTimeoutMsConfig:LX/7yr;

.field public final fixBlackscreenByRecreatingSurface:Z

.field public final fixDRMPlaybackOnHDMI:Z

.field public final fixNullCacheSpan:Z

.field public final fixPeriodTransitionWithNonZeroStartPosition:Z

.field public final fixSurfaceInvisibleParent:Z

.field public final fixXmlParserError:Z

.field public final forceAdjustSurfaceOnMainThread:Z

.field public final forceDisableULL:Z

.field public final forceMainThreadHandlerForHeroSurface:Z

.field public final forceManifestFilteringMode:I

.field public final forceMinWatermarkGreaterThanMinRebuffer:Z

.field public final forceOneSemanticsHandling:Z

.field public final forceOneSemanticsWaveHandling:I

.field public final forceSeekRushPlayback:Z

.field public final forceStereoToMonoConversion:Z

.field public final fragmentedMp4ExtractorVersion:I

.field public final frequentApiTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentBroadcasterStallIntervalThresholdMs:I

.field public final frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentStallIntervalThresholdMs:I

.field public final fullscreenPredictionRequestTimeoutMs:J

.field public final getMinLoadPositionStartOfPlayback:Z

.field public final getPlaybackPrefFromPrefetchRequest:Z

.field public final globalStallCountsToUpdateDynamicRebuffer:I

.field public final globalStallCountsToUpdateLiveDynamicRebuffer:I

.field public final goodVsrScoreThreshold:I

.field public final handleReleasedReusedSurfaceTexture:Z

.field public final handlerThreadPoolSize:I

.field public final highJumpDistanceMs:I

.field public final huddleLatencyMaxSpeedDelta:F

.field public final ignore404AfterStreamEnd:Z

.field public final ignoreEmptyProfileLevels:Z

.field public final ignoreLiveStreamErrorsTimeoutMs:J

.field public final ignoreStreamErrorsTimeoutMs:J

.field public final ignoreTemplatedMinLoadPosition:Z

.field public final improveLooping:Z

.field public final includeAllBufferingEvents:Z

.field public final includeLiveTraceHeader:Z

.field public final includePlaybackSessionIdHeader:Z

.field public final initChunkCacheSize:I

.field public final initialBufferTrimPeriodMs:I

.field public final initialBufferTrimTargetMs:I

.field public final initialBufferTrimThresholdMs:I

.field public final intentBasedBufferingConfig:LX/7z1;

.field public final isAbrTracingEnabled:Z

.field public final isAudioDataSummaryEnabled:Z

.field public final isDefaultMC:Z

.field public final isEarlyPreallocateCodec:Z

.field public final isExo2AggresiveMicrostallFixEnabled:Z

.field public final isExo2DrmEnabled:Z

.field public final isExo2MediaCodecReuseEnabled:Z

.field public final isExo2UseAbsolutePosition:Z

.field public final isExo2Vp9Enabled:Z

.field public final isLiveTraceEnabled:Z

.field public final isMeDevice:Z

.field public final isSetSerializableBlacklisted:Z

.field public final isTATracingEnabled:Z

.field public final isVideoQplPipelineEnabled:Z

.field public final jumpSeekPosLeftoverBufferDurationMs:I

.field public final jumpSeekReductionFactorPct:I

.field public final killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

.field public final killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

.field public final killVideoProcessWhenMainProcessDead:Z

.field public final largeBandwidthCursorMs:I

.field public final largeBandwidthToleranceMs:I

.field public final largeJumpBandwidthMultiplier:F

.field public final lateNightHourLowerThreshold:I

.field public final lateNightHourUpperThreshold:I

.field public final latencyBoundMsConfig:LX/7yr;

.field public final latencyControllerBypassLimits:Z

.field public final liveAPIMinBufferMsConfig:LX/7yr;

.field public final liveAPIMinRebufferMsConfig:LX/7yr;

.field public final liveBufferDurationFluctuationTolerancePercent:I

.field public final liveBufferMeterTrimByMinBuffer:Z

.field public final liveDashEdgeLatencyMs:I

.field public final liveDashHighWatermarkMs:I

.field public final liveDashLowWatermarkMs:I

.field public final liveEnableStreamingCache:Z

.field public final liveLatencyManagerPlayerFormat:Ljava/lang/String;

.field public final liveLatencySettings:Ljava/util/Map;

.field public final liveMinBufferMsConfig:LX/7yr;

.field public final liveMinRebufferMsConfig:LX/7yr;

.field public final liveMinRetryCounts:I

.field public final livePremiumMinBufferMsConfig:LX/7yr;

.field public final livePremiumMinRebufferMsConfig:LX/7yr;

.field public final livePrioritizeTimeOverSizeThresholds:Z

.field public final liveTrimByBufferMeterMinDeltaMs:I

.field public final liveUseLowPriRequests:Z

.field public final localSocketProxyAddress:Ljava/lang/String;

.field public final logLatencyEvents:Z

.field public final logOnApacheFallback:Z

.field public final logPausedSeekPositionBeforeSettingState:Z

.field public final logStallOnPauseOnError:Z

.field public final loggerSDKConfig:LX/7ys;

.field public final lowJumpDistanceMs:I

.field public final mEventLogSetting:LX/7yk;

.field public final mLowLatencySetting:LX/7yl;

.field public final manifestErrorReportingExo2:Z

.field public final manifestMisalignmentReportingExo2:Z

.field public maxAllowed503RetryCount:I

.field public final maxBufferDurationPausedLiveUs:J

.field public final maxBufferToDownloadInPausedLoadingMs:I

.field public final maxBytesToPrefetchCellVOD:I

.field public final maxBytesToPrefetchVOD:I

.field public final maxCustomizedWABufferMs:I

.field public final maxDistanceBetweenTracksMs:I

.field public final maxDurationUsForFullSegmentPrefetch:J

.field public final maxMediaCodecInstancesPerCodecName:I

.field public final maxMediaCodecInstancesTotal:I

.field public final maxNumGapsToNotify:I

.field public final maxNumRedirects:I

.field public final maxPastOtherTrackDistanceMs:I

.field public final maxPredictedSegmentsToRemap:I

.field public final maxRetryCountByEvictCacheOnExoplayerErrors:I

.field public final maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

.field public final maxSegmentsToAdvance:J

.field public final maxSegmentsToPredict:I

.field public final maxStaleManifestCountForDiscontinuityJumps:I

.field public final maxTimeAllowedSpentInPausedLoadingMs:I

.field public final maxTimeMsSinceRefreshPDash:I

.field public final maxTimeToSkipInlineManifestMs:I

.field public final maxTrackJumpsAllowed:I

.field public final maxWidthForAV1SRShader:I

.field public final maxWifiBytesToPrefetchAds:I

.field public final maxWifiPrefetchDurationMsAds:I

.field public final maybeSkipInlineManifestForLSB:Z

.field public final mcDebugState:Ljava/lang/String;

.field public final mcValueSource:Ljava/lang/String;

.field public final microStallThresholdMsToUseMinBuffer:I

.field public final minBufferForPreSeekMs:J

.field public final minBufferMsConfig:LX/7yr;

.field public final minBufferedDurationMsToCancel:I

.field public minCacheFileSizeForDynamicChunkingInBytes:J

.field public final minCustomizedWABufferMs:I

.field public final minDelayToRefreshTigonBitrateMs:J

.field public final minLiveStartPositionMs:I

.field public final minMicroRebufferMsConfig:LX/7yr;

.field public final minNumManifestForOutOfBoundsPDash:I

.field public final minRebufferMsConfig:LX/7yr;

.field public final minRetryCountBeforePlay:I

.field public final minScoreThresholdForLL:I

.field public final minTimeBetweenDynamicCursorChangesMs:I

.field public final minTimeBetweenStallToIgnoreDiscontJumpS:I

.field public final minTimeToSkipInlineManifestMs:I

.field public final minimumLogLevel:I

.field public final minimumTimeBetweenSpeedChangesS:I

.field public final minimumTimeBetweenStallsS:I

.field public final needUpdatePlayerStateThresholdMs:I

.field public final needUpdateStateByPositionOffsetThresholdMs:I

.field public final networkAwareDisableSecondPhasePrefetch:LX/7yr;

.field public final networkAwareHttpPriorityIncrementalForStreaming:LX/7yr;

.field public final networkAwarePrefetchTaskQueueWorkerNum:LX/7yr;

.field public final newDownstreamFormatChange:Z

.field public final numDashChunkMemoryCacheSampleStreams:I

.field public final numMsToPrefetch:I

.field public final numOfBytesBeforeLoaderThreadSleep:I

.field public final numSegmentsToSecondPhasePrefetch:I

.field public final numSegmentsToSecondPhasePrefetchAudio:I

.field public final numSegmentsToSecondPhasePrefetchXHEAACAudio:I

.field public final offloadGrootAudioFocus:Z

.field public final oneSemanticsOsParamValue:Ljava/lang/String;

.field public final originAllowlistForAlternateCodec:Ljava/util/Set;

.field public final parseAndAttachETagManifest:Z

.field public final parseManifestIdentifier:Z

.field public final pausePlayingVideoWhenRelease:Z

.field public final pausedLoadingTriggerTypes:Ljava/util/Set;

.field public final pidMultiplierFloor:F

.field public final pidParameterExpBackOff:F

.field public final pidParameterMultiplierInitial:F

.field public final playbackAboutToFinishCallbackTriggeringRemainingDuration:I

.field public final playerOriginPausedLoadingBlackList:Ljava/lang/String;

.field public final playerPoolSize:I

.field public final playerRespawnExo2:Z

.field public final playerWarmUpPoolSize:I

.field public final playerWarmUpWatermarkMs:I

.field public final playerWatermarkBeforePlayedMs:I

.field public final postStoriesGrootPrefetchToHeroManagerThread:Z

.field public final predictedHuddleDashManifestReadTimeoutMs:I

.field public final predictedLiveDashManifestReadTimeoutMs:I

.field public final predictionMaxSegmentDurationMs:I

.field public final predictiveDashReadTimeoutMs:I

.field public final predictiveDashSetting:LX/7z8;

.field public final prefetchAudioFirst:Z

.field public final prefetchAudioFirstForStoriesAds:Z

.field public final prefetchBypassFilter:Z

.field public final prefetchSubOriginBlockList:Ljava/lang/String;

.field public final prefetchTagBlockList:Ljava/lang/String;

.field public final prefetchTaskQueuePutInFront:Z

.field public final prefetchTaskQueueRetryNumber:I

.field public final prefetchTaskQueueSize:I

.field public final prefetchTaskQueueWorkerNum:I

.field public final prefetchThreadUpdatedPriority:I

.field public final prefetchUrgentTaskQueueWorkerNum:I

.field public final preventAdjustWhenSurfaceNotValid:Z

.field public final preventJumpStaticManifest:Z

.field public final preventPreallocateIfNotEmpty:Z

.field public final preventTextRendererDelay:Z

.field public final preventWarmupInvalidSource:Z

.field public final prioritizeAv1Dav1dOverLibgav1:Z

.field public final prioritizeAv1HardwareDecoder:Z

.field public final prioritizeTimeOverSizeThresholds:Z

.field public final progressivePrefetchBytesCell:I

.field public final progressivePrefetchBytesWifi:I

.field public final proxyDrmProvisioningRequests:Z

.field public final qualityMapperBoundMsConfig:LX/7yr;

.field public final quitHandlerSafely:Z

.field public final redMemoryBufferSizeMultiplier:D

.field public final reduceMemoryDataSinkMemorySpike:Z

.field public final refreshManifestAfterInit:Z

.field public final refreshManifestOnPredictionRestriction:Z

.field public final releaseGrootSurfaceSync:Z

.field public final releaseHeroManagerWhenLowMemInBg:Z

.field public final releaseSurfaceBlockTimeoutMS:I

.field public final releaseSurfaceInServicePlayerReset:Z

.field public final releaseThreadInterval:I

.field public final removeGifPrefixForDRMKeyRequest:Z

.field public final renderRetryTimeMs:I

.field public final rendererAllowedJoiningTimeMs:J

.field public final reorderSeekPrepare:Z

.field public final reportExceptionAsMME:Z

.field public final reportExceptionsAsSoftErrors:Z

.field public final reportLastVideoInCrash:Z

.field public final reportPrefetchAbrDecision:Z

.field public final reportStallThresholdMs:I

.field public final reportStallThresholdMsLatencyManager:I

.field public final reportUnexpectedStopLoading:Z

.field public final resizeAndRepositionGrootSurfaceControl:Z

.field public final respectAbrForUll:Z

.field public final respectAbrIndexForUll:Z

.field public final respectDroppedQualityFlag:Z

.field public final respectDynamicPlayerSettings:Z

.field public final restartServiceThresholdMs:I

.field public final retryCountsForStartPlayManifest503:I

.field public final retryCountsForStartPlayManifestFetch:I

.field public final returnRequestedSeekTimeTimeoutMs:I

.field public final saturationFactor:F

.field public final scalingBufferErrorMs:I

.field public final sdKVersionToUseCustomizedBuffering:I

.field public final sdkVersionToUseConservativeLoadControl:I

.field public final sdkVersionToUseDefaultLoadControl:I

.field public final secondPhasePrefetchQueueMaxSize:I

.field public final secondaryChannelLoggingMaxDisplayedFramesStringSize:I

.field public final secondaryChannelLoggingMaxNumOfFramesInOneJson:I

.field public final secondaryChannelLoggingSamplingFactor:I

.field public final seekParameterOptionIndex:I

.field public final segDurationMultiplier:I

.field public final serviceInjectorClassName:Ljava/lang/String;

.field public final setPlayWhenReadyOnError:Z

.field public final setPlayWhenReadyOnRetry:Z

.field public final shareBWEEstimateAcrossVideos:Z

.field public final shouldAddDefaultMP4Extractor:Z

.field public final shouldAlwaysDo503Retry:Z

.field public final shouldCleanupHeroManagerThread:Z

.field public final shouldDisableAV1VideoTrackOnlyforVDD:Z

.field public final shouldExcludeAbsolutePositionForClippingMediaSource:Z

.field public final shouldLoadBinaryDataFromManifest:Z

.field public final shouldLogInbandTelemetryBweDebugString:Z

.field public final shouldPrefetchSecondSegmentOffset:Z

.field public final shouldUseWarmupSlot:Z

.field public final shouldWarmupAwareOfAppScrolling:Z

.field public final showDebugStats:Z

.field public final skipAV1PreviousKeyFrameSeek:Z

.field public final skipAudioMediaCodecStopOnRelease:Z

.field public final skipAudioPrefetch:Z

.field public final skipDebugLogs:Z

.field public final skipEvaluateIflastChunkWasInitialization:Z

.field public final skipInlineManifestForLsbConfPercentile:I

.field public final skipInvalidSamples:Z

.field public final skipMediaCodecStopOnRelease:Z

.field public final skipPrefetchInCacheManager:Z

.field public final skipReleaseSurfaceBlock:Z

.field public final skipSurfaceViewReparentOnSetCurrentView:Z

.field public final skipSurfaceViewTransactionOnSameSurface:Z

.field public final skipSynchronizedUpdatePriority:Z

.field public final skipThumbnailCacheKey:Z

.field public final smallBandwidthCursorMs:I

.field public final smallBandwidthToleranceMs:I

.field public final smallJumpBandwidthMultiplier:F

.field public final smartGcEnabled:Z

.field public final smartGcTimeout:I

.field public final softErrorErrorCodeBlacklist:Ljava/util/Set;

.field public final softErrorErrorDomainBlacklist:Ljava/util/Set;

.field public final softErrorErrorMessageBlacklist:Ljava/util/Set;

.field public final sortSubripSubtitles:Z

.field public final splitBweOnRadio:Z

.field public final splitLastSegmentCachekey:Z

.field public final ssAbrAlphaDecay:F

.field public final ssAbrExperimentSetting:Ljava/lang/String;

.field public final ssAbrMinSamples:I

.field public final ssAbrNumSamplesAvg:I

.field public final staleManifestThreshold:I

.field public final staleManifestThresholdToShowInterruptUI:I

.field public final stallCountsToUpdateDynamicRebufferThreshold:I

.field public final stallFromSeekThresholdMs:I

.field public final stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

.field public final streamLatencyToggleMaxSpeedDelta:F

.field public final streamLatencyTogglePIDDesiredBufferMs:I

.field public final streamLatencyTogglePIDIntegralBoundMs:I

.field public final streamLatencyToggleSpeedUpBandwidthMultiplier:F

.field public final streamLatencyToggleStateOverride:I

.field public final subtitleDurationToMaxValue:Z

.field public final surfaceControlForceVideoSizeUpdate:Z

.field public final surfaceMPDFailoverImmediately:Z

.field public final swallowSurfaceGlDetachError:Z

.field public final targetBufferBytesFactor:F

.field public final timeBetweenPIDSamplesMs:I

.field public final tslogSettings:LX/7yn;

.field public final unstallBufferSetting:LX/7z3;

.field public final unstallBufferSettingLive:LX/7z3;

.field public final updateConcatMsDuringPlayback:Z

.field public final updateLoadingPriorityExo2:Z

.field public final updateParamOnGetManifestFetcher:Z

.field public final updateUnstallBufferDuringPlayback:Z

.field public final useAccumulatorForBw:Z

.field public final useAdAwareLoadControl:Z

.field public final useAllSettingsToSupportLowerLatency:Z

.field public final useBackgroundHandlerForHeroLiveManager:Z

.field public final useBlockingSetSurfaceExo2:Z

.field public final useBufferBasedAbrPDash:Z

.field public final useBufferedCacheDataSink:Z

.field public final useBwBpsForConnectionQuality:Z

.field public final useCellMaxWaterMarkMsConfig:Z

.field public final useCodecNeedsEosBufferTimestampWorkaround:Z

.field public final useDummySurfaceExo2:Z

.field public final useExoPlayerBuilder:Z

.field public final useFallbackLogging:Z

.field public final useForceSurfaceChange:Z

.field public final useFullscreenTransitionPrediction:Z

.field public final useHandlerThreadPool:Z

.field public final useHeroBufferSize:Z

.field public final useHttpPriorityIncrementalForLongBufferedStreaming:Z

.field public final useHttpPriorityIncrementalForPrefetch:Z

.field public final useHttpPriorityIncrementalForStreaming:Z

.field public final useHttpPriorityWarmupForLongBufferedStreaming:Z

.field public final useInterruptedIoException:Z

.field public final useIsCachedSkipInit:Z

.field public final useLatencyForSegmentConcat:Z

.field public final useLowPriorityForSecondPhasePrefetch:Z

.field public final useLowerHttpPriorityForAllPrefetch:Z

.field public final useLowerHttpPriorityForUnimportantPrefetch:Z

.field public final useMainThreadForHeroPlayer:Z

.field public final useMaxBufferForProgressive:Z

.field public final useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

.field public final useMediaCodecPoolingConcurrentCollections:Z

.field public final useMediaCodecPoolingForCodecByName:Ljava/lang/String;

.field public final useMinIntentBasedWatermarkBeforePlay:Z

.field public final useMultiPeriodBufferCalculation:Z

.field public final useNetworkAwareHttpPriorityIncrementalForStreaming:Z

.field public final useNetworkAwareSettingsForLargerChunk:Z

.field public final useNetworkAwareSettingsForUnstallBuffer:Z

.field public final useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

.field public final useNonInterleavedExtractorForLocal:Z

.field public final useOutputSurfaceWorkaround:Z

.field public final usePerVideoLookupToCheckCache:Z

.field public final usePrefetchFilter:Z

.field public final usePrefetchSegmentOffset:Z

.field public final useSSAbrBWE:Z

.field public final useSSAbrMinRtt:Z

.field public final useShortKey:Z

.field public final useSimpleSpeedController:Z

.field public final useSingleCachedBandwidthEstimate:Z

.field public final useSsBweForVod:Z

.field public final useSteadyStateToControlSpeed:Z

.field public final useThreadSafeStandaloneClock:Z

.field public final useVersion2_18Workarounds:Z

.field public final useVideoSourceAsWarmupKey:Z

.field public final useWatermarkEvaluatorForProgressive:Z

.field public final useWifiMaxWaterMarkMsConfig:Z

.field public final userAgent:Ljava/lang/String;

.field public final userId:Ljava/lang/String;

.field public final validateBytesToFallbackOnFirstSegment:Z

.field public final videoBufferSize:I

.field public final videoMemoryCacheSizeKb:I

.field public final videoPrefetchSetting:LX/7yp;

.field public final vp9BlockingReleaseSurface:Z

.field public final vp9PlaybackDecoderName:Ljava/lang/String;

.field public final wakelockOriginLists:Ljava/util/Set;

.field public final warmupAv1Codec:Z

.field public final warmupVp9Codec:Z

.field public final watchTimeThresholdToDisableFollowupPrefetch:F

.field public final watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

.field public final wifiMaxWatermarkMsConfig:LX/7yr;

.field public final xHEAACCEffectType:I

.field public final xHEAACTargetReferenceLvl:I


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    new-instance v1, LX/7Hj;

    invoke-direct {v1}, LX/7Hj;-><init>()V

    new-instance v0, LX/7z9;

    invoke-direct {v0, v1}, LX/7z9;-><init>(LX/7Hj;)V

    sput-object v0, LX/7z9;->A01:LX/7z9;

    new-instance v1, LX/6z9;

    invoke-direct {v1}, LX/6z9;-><init>()V

    new-instance v0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    invoke-direct {v0, v1}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>(LX/6z9;)V

    sput-object v0, LX/7z9;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    return-void
.end method

.method public constructor <init>(LX/7Hj;)V
    .locals 3

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->enableCacheNetworkTypeIfNotSet:Z

    iget-object v0, p1, LX/7Hj;->A0K:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/7z9;->autogenSettings:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-boolean v1, p0, LX/7z9;->improveLooping:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->serviceInjectorClassName:Ljava/lang/String;

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->playerPoolSize:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/7z9;->releaseSurfaceBlockTimeoutMS:I

    iput-boolean v1, p0, LX/7z9;->skipReleaseSurfaceBlock:Z

    iget-object v0, p1, LX/7Hj;->A0R:Ljava/lang/String;

    iput-object v0, p0, LX/7z9;->userAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->userId:Ljava/lang/String;

    const/16 v0, 0x14

    iput v0, p0, LX/7z9;->reportStallThresholdMs:I

    iput v0, p0, LX/7z9;->reportStallThresholdMsLatencyManager:I

    const/16 v0, 0xa

    iput v0, p0, LX/7z9;->checkPlayerStateMinIntervalMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/7z9;->checkPlayerStateMaxIntervalMs:I

    const/4 v0, 0x5

    iput v0, p0, LX/7z9;->checkPlayerStateIntervalIncreaseMs:I

    const/16 v0, 0xfa

    iput v0, p0, LX/7z9;->needUpdatePlayerStateThresholdMs:I

    const/16 v0, 0xa

    iput v0, p0, LX/7z9;->needUpdateStateByPositionOffsetThresholdMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->enablePauseNow:Z

    iput-boolean v1, p0, LX/7z9;->enableFBLiteHttpDataSource:Z

    iput-boolean v1, p0, LX/7z9;->enableLocalSocketProxy:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->localSocketProxyAddress:Ljava/lang/String;

    iput-boolean v1, p0, LX/7z9;->useNonInterleavedExtractorForLocal:Z

    iput-boolean v1, p0, LX/7z9;->enableIgHttpDataSource:Z

    iput-boolean v1, p0, LX/7z9;->enableCaseInsensitiveHttpResponseHeaderKey:Z

    iput-boolean v1, p0, LX/7z9;->usePrefetchFilter:Z

    iput-boolean v1, p0, LX/7z9;->avoidServiceClassLoadOnClient:Z

    iput-boolean v1, p0, LX/7z9;->vp9BlockingReleaseSurface:Z

    iput-object v0, p0, LX/7z9;->vp9PlaybackDecoderName:Ljava/lang/String;

    iput-boolean v1, p0, LX/7z9;->includeAllBufferingEvents:Z

    iget-object v0, p1, LX/7Hj;->A0J:LX/7yt;

    iput-object v0, p0, LX/7z9;->cache:LX/7yt;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->setPlayWhenReadyOnError:Z

    iput-boolean v0, p0, LX/7z9;->setPlayWhenReadyOnRetry:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->returnRequestedSeekTimeTimeoutMs:I

    const/16 v0, 0x1f4

    iput v0, p0, LX/7z9;->stallFromSeekThresholdMs:I

    iput-boolean v1, p0, LX/7z9;->enablePrefetchCancelCallback:Z

    iget-object v0, p1, LX/7Hj;->A0O:LX/7z3;

    iput-object v0, p0, LX/7z9;->unstallBufferSetting:LX/7z3;

    iget-object v0, p1, LX/7Hj;->A0P:LX/7z3;

    iput-object v0, p0, LX/7z9;->unstallBufferSettingLive:LX/7z3;

    iput-boolean v1, p0, LX/7z9;->clearBufferingWhenInWarmup:Z

    iget-object v0, p1, LX/7Hj;->A0L:LX/7z1;

    iput-object v0, p0, LX/7z9;->intentBasedBufferingConfig:LX/7z1;

    iput-boolean v1, p0, LX/7z9;->releaseSurfaceInServicePlayerReset:Z

    iput-boolean v1, p0, LX/7z9;->respectDynamicPlayerSettings:Z

    iput-boolean v1, p0, LX/7z9;->reportPrefetchAbrDecision:Z

    iget-object v0, p1, LX/7Hj;->A0H:LX/7yw;

    iput-object v0, p0, LX/7z9;->abrSetting:LX/7yw;

    iget-object v0, p1, LX/7Hj;->A0G:LX/7z8;

    iput-object v0, p0, LX/7z9;->predictiveDashSetting:LX/7z8;

    iput-boolean v1, p0, LX/7z9;->refreshManifestOnPredictionRestriction:Z

    iget-object v0, p1, LX/7Hj;->A0F:LX/7yu;

    iput-object v0, p0, LX/7z9;->dynamicInfoSetting:LX/7yu;

    iget-object v0, p1, LX/7Hj;->A0E:LX/7yq;

    iput-object v0, p0, LX/7z9;->bandwidthEstimationSetting:LX/7yq;

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->mLowLatencySetting:LX/7yl;

    iput-object v0, p0, LX/7z9;->mEventLogSetting:LX/7yk;

    iget-object v0, p1, LX/7Hj;->A0I:LX/7yo;

    iput-object v0, p0, LX/7z9;->audioLazyLoadSetting:LX/7yo;

    iput-boolean v1, p0, LX/7z9;->enableLazyAudioLoadForProgressive:Z

    iget-object v0, p1, LX/7Hj;->A0Q:LX/7yp;

    iput-object v0, p0, LX/7z9;->videoPrefetchSetting:LX/7yp;

    const/16 v0, 0x3023

    iput v0, p0, LX/7z9;->dashLowWatermarkMs:I

    const/16 v0, 0x3747

    iput v0, p0, LX/7z9;->dashHighWatermarkMs:I

    iput-boolean v1, p0, LX/7z9;->liveEnableStreamingCache:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/7z9;->minDelayToRefreshTigonBitrateMs:J

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->fetchCacheSourceHttpConnectTimeoutMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->fetchHttpReadTimeoutMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->concatenatedMsPerLoadConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->minBufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->minRebufferMsConfig:LX/7yr;

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->enableGrootAlwaysSendPlayStarted:Z

    iput-object v0, p0, LX/7z9;->minMicroRebufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->liveMinBufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->liveMinRebufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->liveAPIMinBufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->liveAPIMinRebufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->livePremiumMinBufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->livePremiumMinRebufferMsConfig:LX/7yr;

    iput-boolean v1, p0, LX/7z9;->useLatencyForSegmentConcat:Z

    iget-object v0, p1, LX/7Hj;->A0C:LX/7yr;

    iput-object v0, p0, LX/7z9;->latencyBoundMsConfig:LX/7yr;

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->fbstoriesMinBufferMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->fbstoriesMinRebufferMsConfig:LX/7yr;

    iget-object v0, p1, LX/7Hj;->A0D:LX/7yr;

    iput-object v0, p0, LX/7z9;->qualityMapperBoundMsConfig:LX/7yr;

    iput-boolean v1, p0, LX/7z9;->enableProgressiveFallbackWhenNoRepresentations:Z

    iput-boolean v1, p0, LX/7z9;->blockDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/7z9;->blockDRMScreenCapture:Z

    iput-boolean v1, p0, LX/7z9;->fixDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/7z9;->enableWarmCodec:Z

    const/4 v0, 0x2

    iput v0, p0, LX/7z9;->playerWarmUpPoolSize:I

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->playerWatermarkBeforePlayedMs:I

    iput v0, p0, LX/7z9;->playerWarmUpWatermarkMs:I

    iput-boolean v1, p0, LX/7z9;->allowOverridingPlayerWarmUpWatermark:Z

    iput-boolean v1, p0, LX/7z9;->swallowSurfaceGlDetachError:Z

    iput-boolean v1, p0, LX/7z9;->forceMainThreadHandlerForHeroSurface:Z

    iput-boolean v1, p0, LX/7z9;->enableWarmupScheduler:Z

    iput-boolean v1, p0, LX/7z9;->enableWarmupSkipScheduler:Z

    iput-boolean v1, p0, LX/7z9;->enableWarmupSchedulerRightAway:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->rendererAllowedJoiningTimeMs:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->skipPrefetchInCacheManager:Z

    iput-boolean v1, p0, LX/7z9;->useNetworkAwareSettingsForLargerChunk:Z

    iput-boolean v1, p0, LX/7z9;->enableDebugLogs:Z

    iput-boolean v1, p0, LX/7z9;->skipDebugLogs:Z

    iput-boolean v1, p0, LX/7z9;->showDebugStats:Z

    iput-boolean v1, p0, LX/7z9;->isAbrTracingEnabled:Z

    iget-boolean v0, p1, LX/7Hj;->A0a:Z

    iput-boolean v0, p0, LX/7z9;->dummyDefaultSetting:Z

    iput-boolean v1, p0, LX/7z9;->enableCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/7z9;->useSingleCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/7z9;->disableTigonBandwidthLogging:Z

    iput-boolean v1, p0, LX/7z9;->shouldLogInbandTelemetryBweDebugString:Z

    iput-boolean v1, p0, LX/7z9;->killVideoProcessWhenMainProcessDead:Z

    iput-boolean v1, p0, LX/7z9;->isLiveTraceEnabled:Z

    iput-boolean v1, p0, LX/7z9;->isTATracingEnabled:Z

    iput-boolean v1, p0, LX/7z9;->releaseGrootSurfaceSync:Z

    iput-boolean v1, p0, LX/7z9;->asyncReleaseSurfaceOnMainThread:Z

    iput-boolean v1, p0, LX/7z9;->preventTextRendererDelay:Z

    iput-boolean v1, p0, LX/7z9;->fixPeriodTransitionWithNonZeroStartPosition:Z

    iput-boolean v1, p0, LX/7z9;->abrMonitorEnabled:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->maxNumGapsToNotify:I

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForVodVideo:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForVodAudio:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForLiveVideo:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForLiveAudio:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForProgressiveVideo:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecPoolingForProgressiveAudio:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecReuseOptimizeLock:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaCodecReuseOptimizeRelease:Z

    iput-boolean v1, p0, LX/7z9;->useMediaCodecPoolingConcurrentCollections:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->useMediaCodecPoolingForCodecByName:Ljava/lang/String;

    iput-boolean v1, p0, LX/7z9;->useVersion2_18Workarounds:Z

    iput-boolean v1, p0, LX/7z9;->useCodecNeedsEosBufferTimestampWorkaround:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->releaseThreadInterval:I

    const/4 v0, 0x2

    iput v0, p0, LX/7z9;->maxMediaCodecInstancesPerCodecName:I

    const/4 v0, 0x4

    iput v0, p0, LX/7z9;->maxMediaCodecInstancesTotal:I

    iput-boolean v1, p0, LX/7z9;->enableAlwaysCallPreallocateCodec:Z

    iput-boolean v1, p0, LX/7z9;->isEarlyPreallocateCodec:Z

    iput-boolean v1, p0, LX/7z9;->earlyPreallocateCodecOnAppNotScrolling:Z

    iput-boolean v1, p0, LX/7z9;->earlyPreallocateCodecOnIdle:Z

    iput-boolean v1, p0, LX/7z9;->disablePreallocateCodecDuringStartup:Z

    iput-boolean v1, p0, LX/7z9;->useNetworkAwareSettingsForUnstallBuffer:Z

    iput-boolean v1, p0, LX/7z9;->disableStoriesCustomizedUnstallBuffer:Z

    iput-boolean v1, p0, LX/7z9;->bgHeroServiceStatusUpdate:Z

    iput-boolean v1, p0, LX/7z9;->isExo2UseAbsolutePosition:Z

    iput-boolean v1, p0, LX/7z9;->shouldExcludeAbsolutePositionForClippingMediaSource:Z

    iput-boolean v1, p0, LX/7z9;->isExo2MediaCodecReuseEnabled:Z

    iput-boolean v1, p0, LX/7z9;->useBlockingSetSurfaceExo2:Z

    iput-boolean v1, p0, LX/7z9;->isExo2AggresiveMicrostallFixEnabled:Z

    iput-boolean v1, p0, LX/7z9;->warmupVp9Codec:Z

    iput-boolean v1, p0, LX/7z9;->warmupAv1Codec:Z

    iget-boolean v0, p1, LX/7Hj;->A0c:Z

    iput-boolean v0, p0, LX/7z9;->playerRespawnExo2:Z

    iput-boolean v1, p0, LX/7z9;->updateLoadingPriorityExo2:Z

    iput-boolean v1, p0, LX/7z9;->checkReadToEndBeforeUpdatingFinalState:Z

    iput-boolean v1, p0, LX/7z9;->isExo2Vp9Enabled:Z

    iput-boolean v1, p0, LX/7z9;->exo2Vp9UseSurfaceRenderer:Z

    iput-boolean v1, p0, LX/7z9;->skipEvaluateIflastChunkWasInitialization:Z

    iput-boolean v1, p0, LX/7z9;->logOnApacheFallback:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->enableSystrace:Z

    iput-boolean v1, p0, LX/7z9;->isDefaultMC:Z

    const-string v0, "unset"

    iput-object v0, p0, LX/7z9;->mcDebugState:Ljava/lang/String;

    iput-object v0, p0, LX/7z9;->mcValueSource:Ljava/lang/String;

    iput-boolean v1, p0, LX/7z9;->enableCodecPreallocation:Z

    iput-boolean v1, p0, LX/7z9;->enableVp9CodecPreallocation:Z

    iput-boolean v1, p0, LX/7z9;->preventPreallocateIfNotEmpty:Z

    iput-boolean v1, p0, LX/7z9;->enableRequestEtdHeader:Z

    iput-boolean v1, p0, LX/7z9;->reportLastVideoInCrash:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->maxDurationUsForFullSegmentPrefetch:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->isSetSerializableBlacklisted:Z

    iput-boolean v1, p0, LX/7z9;->useWatermarkEvaluatorForProgressive:Z

    iput-boolean v1, p0, LX/7z9;->useMaxBufferForProgressive:Z

    iget-boolean v0, p1, LX/7Hj;->A0g:Z

    iput-boolean v0, p0, LX/7z9;->useDummySurfaceExo2:Z

    iput-boolean v1, p0, LX/7z9;->useVideoSourceAsWarmupKey:Z

    const-wide/32 v0, 0x5b8d80

    iput-wide v0, p0, LX/7z9;->maxBufferDurationPausedLiveUs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableUsingASRCaptions:Z

    iput-boolean v0, p0, LX/7z9;->enableBitrateAwareAudioPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->proxyDrmProvisioningRequests:Z

    iput-boolean v0, p0, LX/7z9;->liveUseLowPriRequests:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->liveDashEdgeLatencyMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->logLatencyEvents:Z

    iput-boolean v0, p0, LX/7z9;->disableLatencyManagerOnStaticManifest:Z

    iput-boolean v0, p0, LX/7z9;->enablePreSeekToApi:Z

    iput-boolean v0, p0, LX/7z9;->continuouslyLoadFromPreSeekLocation:Z

    const-wide v0, 0x7fffffffffffffffL

    iput-wide v0, p0, LX/7z9;->minBufferForPreSeekMs:J

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->audioVideoSyncPeriodMs:I

    iput-boolean v0, p0, LX/7z9;->enableProgressivePrefetchWhenNoRepresentations:Z

    iput-boolean v0, p0, LX/7z9;->continueLoadingOnSeekbarExo2:Z

    iput-boolean v0, p0, LX/7z9;->subtitleDurationToMaxValue:Z

    iput-boolean v0, p0, LX/7z9;->isExo2DrmEnabled:Z

    iput-boolean v0, p0, LX/7z9;->enableDrmProvisioningRetry:Z

    iput-boolean v0, p0, LX/7z9;->sortSubripSubtitles:Z

    iput-boolean v0, p0, LX/7z9;->logStallOnPauseOnError:Z

    iput-boolean v0, p0, LX/7z9;->skipSynchronizedUpdatePriority:Z

    iput-boolean v0, p0, LX/7z9;->exo2ReuseManifestAfterInitialParse:Z

    iput-boolean v0, p0, LX/7z9;->enableFrameBasedLogging:Z

    const/16 v0, 0x64

    iput v0, p0, LX/7z9;->prefetchTaskQueueSize:I

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->prefetchTaskQueueWorkerNum:I

    const/4 v0, 0x2

    iput v0, p0, LX/7z9;->prefetchUrgentTaskQueueWorkerNum:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->usePrefetchSegmentOffset:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->refreshManifestAfterInit:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->disableAudioFocusInGroot:Z

    iput-boolean v0, p0, LX/7z9;->offloadGrootAudioFocus:Z

    iput-boolean v0, p0, LX/7z9;->enableDeduplicateImfEmsgAtPlayer:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->numMsToPrefetch:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableWifiLongerPrefetchAds:Z

    iput-boolean v0, p0, LX/7z9;->enableAllLongerPrefetchAds:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->maxWifiPrefetchDurationMsAds:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->adBreakEnahncedPrefetchDurationMs:I

    iput-boolean v0, p0, LX/7z9;->enableAdBreakEnhancedPrefetch:Z

    const/high16 v0, 0x100000

    iput v0, p0, LX/7z9;->maxWifiBytesToPrefetchAds:I

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->minLiveStartPositionMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

    const/16 v0, 0x2ee0

    iput v0, p0, LX/7z9;->liveDashHighWatermarkMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->liveDashLowWatermarkMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->prefetchTaskQueuePutInFront:Z

    iput v0, p0, LX/7z9;->prefetchTaskQueueRetryNumber:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableCancelOngoingRequestPause:Z

    iput-boolean v0, p0, LX/7z9;->shouldPrefetchSecondSegmentOffset:Z

    iput-boolean v0, p0, LX/7z9;->fallbackToFirstSegment:Z

    iput-boolean v0, p0, LX/7z9;->enableSegmentIndexCheckForPrefetchBytes:Z

    iput-boolean v0, p0, LX/7z9;->validateBytesToFallbackOnFirstSegment:Z

    const-string v2, ""

    iput-object v2, p0, LX/7z9;->prefetchTagBlockList:Ljava/lang/String;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->enabledViewManagementInGroot:Z

    const/high16 v0, 0x20000

    iput v0, p0, LX/7z9;->maxBytesToPrefetchVOD:I

    const/high16 v0, 0x10000

    iput v0, p0, LX/7z9;->maxBytesToPrefetchCellVOD:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableLiveOneTimeLoadingJump:Z

    iput-boolean v0, p0, LX/7z9;->enableSpatialOpusRendererExo2:Z

    iput-boolean v0, p0, LX/7z9;->manifestErrorReportingExo2:Z

    iput-boolean v0, p0, LX/7z9;->manifestMisalignmentReportingExo2:Z

    iput-boolean v0, p0, LX/7z9;->enableVideoHybridCache:Z

    iput-boolean v0, p0, LX/7z9;->enableHybridCacheForPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->enableVideoMemoryCache:Z

    const v0, 0x18aa0

    iput v0, p0, LX/7z9;->videoMemoryCacheSizeKb:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->alwaysPerformContentLengthUpdateFirst:Z

    iput-boolean v0, p0, LX/7z9;->enableUpdateProgressiveContentLengthFromCache:Z

    iput-boolean v0, p0, LX/7z9;->enableLongCacheKeyForContentLength:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->updateParamOnGetManifestFetcher:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->prefetchBypassFilter:Z

    iput-boolean v0, p0, LX/7z9;->useBufferBasedAbrPDash:Z

    const/4 v0, 0x5

    iput v0, p0, LX/7z9;->minimumLogLevel:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->isMeDevice:Z

    iput-boolean v0, p0, LX/7z9;->enableOffloadingIPC:Z

    iput-boolean v0, p0, LX/7z9;->pausePlayingVideoWhenRelease:Z

    iput-boolean v0, p0, LX/7z9;->enableAv1Dav1d:Z

    iput-boolean v0, p0, LX/7z9;->enableAv1LibGav1:Z

    iput-boolean v0, p0, LX/7z9;->prioritizeAv1HardwareDecoder:Z

    iget-object v0, p1, LX/7Hj;->A0S:Ljava/util/HashMap;

    iput-object v0, p0, LX/7z9;->blockListedHardwareDecoderMap:Ljava/util/HashMap;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->prioritizeAv1Dav1dOverLibgav1:Z

    iput v0, p0, LX/7z9;->dav1dThreads:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->handleReleasedReusedSurfaceTexture:Z

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->dav1dMaxFrameDelay:I

    iput-boolean v0, p0, LX/7z9;->dav1dApplyGrain:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->av1SetBuffersDataspace:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->av1UseMemoryCleanupFixes:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->av1UseDav1dSynchronizationFixes:Z

    iput-boolean v0, p0, LX/7z9;->av1FlushDav1dProperly:Z

    iput-boolean v0, p0, LX/7z9;->useForceSurfaceChange:Z

    iput-boolean v0, p0, LX/7z9;->parseAndAttachETagManifest:Z

    iput-boolean v0, p0, LX/7z9;->enableSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/7z9;->disableSecondPhasePrefetchForReels:Z

    iput-boolean v0, p0, LX/7z9;->disableSecondPhasePrefetchForDataSaver:Z

    iput-boolean v0, p0, LX/7z9;->enableSecondPhasePrefetchWebm:Z

    iput-boolean v0, p0, LX/7z9;->disableSecondPhasePrefetchOnAppScrolling:Z

    iput-boolean v0, p0, LX/7z9;->enableSecondPhaseAlignment:Z

    iput v0, p0, LX/7z9;->secondPhasePrefetchQueueMaxSize:I

    iput v0, p0, LX/7z9;->numSegmentsToSecondPhasePrefetch:I

    iput v0, p0, LX/7z9;->numSegmentsToSecondPhasePrefetchAudio:I

    iput v0, p0, LX/7z9;->numSegmentsToSecondPhasePrefetchXHEAACAudio:I

    iput-boolean v0, p0, LX/7z9;->enableLogSemiCachedEvents:Z

    iput-boolean v0, p0, LX/7z9;->enableCacheBlockWithoutTimeout:Z

    iput-boolean v0, p0, LX/7z9;->enableLogExceptionMessageOnError:Z

    iput-boolean v0, p0, LX/7z9;->reportExceptionsAsSoftErrors:Z

    iput-boolean v0, p0, LX/7z9;->reportExceptionAsMME:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->checkCachedLockedCacheSpan:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->prefetchAudioFirst:Z

    iput-boolean v0, p0, LX/7z9;->cancelOngoingRequest:Z

    iput-boolean v0, p0, LX/7z9;->enableCancelPrefetchInQueuePrepare:Z

    iput-boolean v0, p0, LX/7z9;->enableBoostOngoingPrefetchPriorityPrepare:Z

    iput-boolean v0, p0, LX/7z9;->enableBoostOngoingPrefetchPriorityPlay:Z

    iput-boolean v0, p0, LX/7z9;->enableDemoteOngoingPrefetchPriorityPause:Z

    iput-boolean v0, p0, LX/7z9;->enableCancelOngoingPrefetchPause:Z

    iput-boolean v0, p0, LX/7z9;->enableCancelFollowupPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->prefetchAudioFirstForStoriesAds:Z

    iput-boolean v0, p0, LX/7z9;->skipAudioPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->allowOutOfBoundsAccessForPDash:Z

    iput v0, p0, LX/7z9;->minNumManifestForOutOfBoundsPDash:I

    iput-boolean v0, p0, LX/7z9;->enableNeedCenteringIndependentlyGroot:Z

    iput-boolean v0, p0, LX/7z9;->av1ThrowExceptionOnPictureError:Z

    iput-boolean v0, p0, LX/7z9;->av1ThrowExceptionOnNonDav1dDecoder:Z

    iget-wide v0, p1, LX/7Hj;->A0B:J

    iput-wide v0, p0, LX/7z9;->ignoreStreamErrorsTimeoutMs:J

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->ignoreLiveStreamErrorsTimeoutMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->callbackFirstCaughtStreamError:Z

    iput-boolean v0, p0, LX/7z9;->avoidSecondPhaseOnCell:Z

    iput-boolean v0, p0, LX/7z9;->includeLiveTraceHeader:Z

    iput-boolean v0, p0, LX/7z9;->alwaysReuseManifestFetcher:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->av1Dav1dEnableVpsLogging:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->av1Dav1dUseSurfaceViewSetFix:Z

    iput-boolean v0, p0, LX/7z9;->skipSurfaceViewReparentOnSetCurrentView:Z

    iput-boolean v0, p0, LX/7z9;->skipSurfaceViewTransactionOnSameSurface:Z

    iput-boolean v0, p0, LX/7z9;->allowMultiPlayerFormatWarmup:Z

    iput-boolean v0, p0, LX/7z9;->reorderSeekPrepare:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->prioritizeTimeOverSizeThresholds:Z

    iput-boolean v0, p0, LX/7z9;->livePrioritizeTimeOverSizeThresholds:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->disableCapBufferSizeLocalProgressive:Z

    iput-boolean v0, p0, LX/7z9;->useHeroBufferSize:Z

    iput v0, p0, LX/7z9;->videoBufferSize:I

    iput v0, p0, LX/7z9;->audioBufferSize:I

    iput-boolean v0, p0, LX/7z9;->enableMemoryAwareBufferSizeUsingRed:Z

    iput-boolean v0, p0, LX/7z9;->enableMemoryAwareBufferSizeUsingYellow:Z

    const-wide/high16 v0, 0x3ff0000000000000L    # 1.0

    iput-wide v0, p0, LX/7z9;->redMemoryBufferSizeMultiplier:D

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->useAccumulatorForBw:Z

    iput-boolean v0, p0, LX/7z9;->parseManifestIdentifier:Z

    iput-boolean v0, p0, LX/7z9;->enableCDNDebugHeaders:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->maxTimeMsSinceRefreshPDash:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->predictionMaxSegmentDurationMs:I

    const/16 v0, 0x2134

    iput v0, p0, LX/7z9;->predictiveDashReadTimeoutMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->segDurationMultiplier:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/7z9;->predictedHuddleDashManifestReadTimeoutMs:I

    iput v0, p0, LX/7z9;->predictedLiveDashManifestReadTimeoutMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableServerSideAbr:Z

    iput-boolean v0, p0, LX/7z9;->enableServerSideForwardBwe:Z

    iput-boolean v0, p0, LX/7z9;->useSSAbrBWE:Z

    iput-boolean v0, p0, LX/7z9;->useSSAbrMinRtt:Z

    iput-boolean v0, p0, LX/7z9;->useSsBweForVod:Z

    iput-boolean v0, p0, LX/7z9;->enableSsBweHeaderForLive:Z

    iput-boolean v0, p0, LX/7z9;->shareBWEEstimateAcrossVideos:Z

    iput-boolean v0, p0, LX/7z9;->splitBweOnRadio:Z

    const v0, 0x7a120

    iput v0, p0, LX/7z9;->progressivePrefetchBytesWifi:I

    const v0, 0x3e800

    iput v0, p0, LX/7z9;->progressivePrefetchBytesCell:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->maxSegmentsToPredict:I

    iput-boolean v0, p0, LX/7z9;->getMinLoadPositionStartOfPlayback:Z

    const v0, 0x3f4ccccd    # 0.8f

    iput v0, p0, LX/7z9;->largeJumpBandwidthMultiplier:F

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/7z9;->smallJumpBandwidthMultiplier:F

    const/16 v0, 0x7d0

    iput v0, p0, LX/7z9;->highJumpDistanceMs:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/7z9;->lowJumpDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableDynamicDiscontinuityDistance:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->dynamicDiscontinuityInitialPosMs:I

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->maxStaleManifestCountForDiscontinuityJumps:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/7z9;->minTimeBetweenDynamicCursorChangesMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableDynamicCursorDistance:Z

    const/16 v0, 0x7d0

    iput v0, p0, LX/7z9;->largeBandwidthCursorMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->smallBandwidthCursorMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/7z9;->largeBandwidthToleranceMs:I

    iput v0, p0, LX/7z9;->smallBandwidthToleranceMs:I

    const/16 v0, 0x3c

    iput v0, p0, LX/7z9;->minimumTimeBetweenStallsS:I

    const/16 v0, 0x1e

    iput v0, p0, LX/7z9;->minimumTimeBetweenSpeedChangesS:I

    const/4 v0, 0x5

    iput v0, p0, LX/7z9;->minTimeBetweenStallToIgnoreDiscontJumpS:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->ignoreTemplatedMinLoadPosition:Z

    iput-boolean v0, p0, LX/7z9;->preventJumpStaticManifest:Z

    iput-boolean v0, p0, LX/7z9;->maybeSkipInlineManifestForLSB:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->disableSkipInlineForHuddle:Z

    const/16 v0, 0x4b

    iput v0, p0, LX/7z9;->skipInlineManifestForLsbConfPercentile:I

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/7z9;->bandwidthMultiplierToSkipPrefetchedContent:F

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->maxTimeToSkipInlineManifestMs:I

    iput v0, p0, LX/7z9;->minTimeToSkipInlineManifestMs:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->aggressiveEdgeLatencyOverrideForLSB:J

    const/16 v0, 0x4b

    iput v0, p0, LX/7z9;->aggressiveEdgeLatencyForLsbConfPercentile:I

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/7z9;->bandwidthMultiplierForAggressiveEdgeLatency:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableLatencyPlaybackSpeed:Z

    iput-boolean v0, p0, LX/7z9;->useSimpleSpeedController:Z

    iput-boolean v0, p0, LX/7z9;->useSteadyStateToControlSpeed:Z

    const v0, 0x3f866666    # 1.05f

    iput v0, p0, LX/7z9;->expBackOffSpeedUp:F

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/7z9;->watchTimeThresholdToDisableFollowupPrefetch:F

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/7z9;->pidMultiplierFloor:F

    const v0, 0x3f99999a    # 1.2f

    iput v0, p0, LX/7z9;->pidParameterMultiplierInitial:F

    const v0, 0x3f733333    # 0.95f

    iput v0, p0, LX/7z9;->pidParameterExpBackOff:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableLiveLatencyManager:Z

    iput-boolean v0, p0, LX/7z9;->enableLiveJumpByTrimBuffer:Z

    iput-boolean v0, p0, LX/7z9;->enableLatencyManagerRateLimiting:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->forceSeekRushPlayback:Z

    iput-object v2, p0, LX/7z9;->liveLatencyManagerPlayerFormat:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableLiveBufferMeter:Z

    iput-boolean v0, p0, LX/7z9;->enableLiveBWEstimation:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->liveTrimByBufferMeterMinDeltaMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableAvc1ColorConfigParseFix:Z

    const/16 v0, 0x14

    iput v0, p0, LX/7z9;->liveBufferDurationFluctuationTolerancePercent:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->liveBufferMeterTrimByMinBuffer:Z

    iput-boolean v0, p0, LX/7z9;->enableSuspensionAfterBroadcasterStall:Z

    iput-boolean v0, p0, LX/7z9;->allowImmediateLiveBufferTrim:Z

    const/16 v0, 0x1388

    iput v0, p0, LX/7z9;->initialBufferTrimPeriodMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/7z9;->initialBufferTrimThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->initialBufferTrimTargetMs:I

    iput v0, p0, LX/7z9;->extendedLiveRebufferThresholdMs:I

    iput v0, p0, LX/7z9;->allowedExtendedRebufferPeriodMs:I

    const/16 v0, 0x7530

    iput v0, p0, LX/7z9;->frequentBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/7z9;->extendedPremiumTierLiveRebufferThresholdMs:I

    const/16 v0, 0x2710

    iput v0, p0, LX/7z9;->allowedExtendedPremiumTierRebufferPeriodMs:I

    const v0, 0xea60

    iput v0, p0, LX/7z9;->frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/7z9;->extendedApiTierLiveRebufferThresholdMs:I

    const v0, 0xea60

    iput v0, p0, LX/7z9;->frequentApiTierBroadcasterStallIntervalThresholdMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableLiveTierSpecificRebuffer:Z

    iput-boolean v0, p0, LX/7z9;->enableMP3Extractor:Z

    iput-boolean v0, p0, LX/7z9;->enableMp3Mp4ExtractorLogic:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->maxNumRedirects:I

    const-string v0, "FB4A/Facebook"

    iput-object v0, p0, LX/7z9;->defaultUserAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->splitLastSegmentCachekey:Z

    iput-boolean v0, p0, LX/7z9;->enableEmsgPtsAlignment:Z

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->fragmentedMp4ExtractorVersion:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enablePlayerActionStateLoggingInFlytrap:Z

    iput-boolean v0, p0, LX/7z9;->enableWarmUpRequestOffscreen:Z

    iput-boolean v0, p0, LX/7z9;->enableFirstWarmUpRequestOnScreen:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->newDownstreamFormatChange:Z

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->microStallThresholdMsToUseMinBuffer:I

    iput-boolean v0, p0, LX/7z9;->updateUnstallBufferDuringPlayback:Z

    iput-boolean v0, p0, LX/7z9;->updateConcatMsDuringPlayback:Z

    iput-boolean v0, p0, LX/7z9;->enableVodDrmPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->enableActiveDrmSessionStoreRelease:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->drmSessionStoreCapacity:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableCustomizedXHEAACConfig:Z

    iput-boolean v0, p0, LX/7z9;->enableSeamlessAudioCodecAdaptation:Z

    iput-boolean v0, p0, LX/7z9;->enableCustomizedDRCEffect:Z

    iput-boolean v0, p0, LX/7z9;->enableCustomizedDRCForHeadset:Z

    const/16 v0, 0x12

    iput v0, p0, LX/7z9;->lateNightHourLowerThreshold:I

    const/4 v0, 0x6

    iput v0, p0, LX/7z9;->lateNightHourUpperThreshold:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableAsynchronousBufferQueueing:Z

    iput-boolean v0, p0, LX/7z9;->enableSynchronizeCodecInteractionsWithQueueing:Z

    iput-boolean v0, p0, LX/7z9;->enableLowLatencyDecoding:Z

    iput-boolean v0, p0, LX/7z9;->enableLowLatencyDecodingOverrideSDKGating:Z

    const/16 v0, 0x40

    iput v0, p0, LX/7z9;->xHEAACTargetReferenceLvl:I

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->xHEAACCEffectType:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->useBwBpsForConnectionQuality:Z

    iput-boolean v0, p0, LX/7z9;->preventWarmupInvalidSource:Z

    iput-boolean v0, p0, LX/7z9;->reportUnexpectedStopLoading:Z

    iput-boolean v0, p0, LX/7z9;->enableReduceRetryBeforePlay:Z

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->minRetryCountBeforePlay:I

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->forceMinWatermarkGreaterThanMinRebuffer:Z

    iput-boolean v1, p0, LX/7z9;->bypassGreaterThanMinRebufferWhenBeforePlay:Z

    iput-boolean v1, p0, LX/7z9;->useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

    iput-boolean v1, p0, LX/7z9;->useWifiMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/7z9;->useCellMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/7z9;->useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/7z9;->wifiMaxWatermarkMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->cellMaxWatermarkMsConfig:LX/7yr;

    iput-object v0, p0, LX/7z9;->networkAwareDisableSecondPhasePrefetch:LX/7yr;

    iput-object v0, p0, LX/7z9;->networkAwarePrefetchTaskQueueWorkerNum:LX/7yr;

    iput-object v0, p0, LX/7z9;->networkAwareHttpPriorityIncrementalForStreaming:LX/7yr;

    iput-boolean v1, p0, LX/7z9;->skipInvalidSamples:Z

    iput v1, p0, LX/7z9;->minBufferedDurationMsToCancel:I

    iput v1, p0, LX/7z9;->decoderInitializationRetryTimeMs:I

    iput v1, p0, LX/7z9;->decoderDequeueRetryTimeMs:I

    iput v1, p0, LX/7z9;->renderRetryTimeMs:I

    iput-boolean v1, p0, LX/7z9;->disableRecoverInBackground:Z

    iput-boolean v1, p0, LX/7z9;->enableEnsureBindService:Z

    iput-boolean v1, p0, LX/7z9;->enableFallbackToMainProcess:Z

    iput-boolean v1, p0, LX/7z9;->enableKillProcessBeforeRebind:Z

    iput v1, p0, LX/7z9;->restartServiceThresholdMs:I

    iput-boolean v1, p0, LX/7z9;->fixSurfaceInvisibleParent:Z

    iput v1, p0, LX/7z9;->depthTocheckSurfaceInvisibleParent:I

    iput-boolean v1, p0, LX/7z9;->isAudioDataSummaryEnabled:Z

    iput-boolean v1, p0, LX/7z9;->enableBlackscreenDetector:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/7z9;->blackscreenSampleIntervalMs:J

    const-wide/16 v0, 0x3e8

    iput-wide v0, p0, LX/7z9;->blackscreenNoSampleThresholdMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->blackscreenDetectOnce:Z

    iput-boolean v0, p0, LX/7z9;->fixBlackscreenByRecreatingSurface:Z

    iput-boolean v0, p0, LX/7z9;->removeGifPrefixForDRMKeyRequest:Z

    iput-boolean v0, p0, LX/7z9;->enableDrmSessionStore:Z

    iput-boolean v0, p0, LX/7z9;->skipMediaCodecStopOnRelease:Z

    iget-object v0, p1, LX/7Hj;->A0X:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->softErrorErrorDomainBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/7Hj;->A0W:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->softErrorErrorCodeBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/7Hj;->A0Y:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->softErrorErrorMessageBlacklist:Ljava/util/Set;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->logPausedSeekPositionBeforeSettingState:Z

    iput-boolean v0, p0, LX/7z9;->enableRetryWarmup:Z

    const/16 v0, 0x64

    iput v0, p0, LX/7z9;->initChunkCacheSize:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->skipAudioMediaCodecStopOnRelease:Z

    iput-boolean v0, p0, LX/7z9;->enableCodecDeadlockFix:Z

    iget v0, p1, LX/7Hj;->A04:I

    iput v0, p0, LX/7z9;->frequentStallIntervalThresholdMs:I

    iget v0, p1, LX/7Hj;->A0A:I

    iput v0, p0, LX/7z9;->stallCountsToUpdateDynamicRebufferThreshold:I

    iget v0, p1, LX/7Hj;->A03:I

    iput v0, p0, LX/7z9;->extendedMinRebufferThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/7z9;->allowedExtendedMinRebuffePeriodMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->fixXmlParserError:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->globalStallCountsToUpdateDynamicRebuffer:I

    iput v0, p0, LX/7z9;->globalStallCountsToUpdateLiveDynamicRebuffer:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableEvictPlayerOnAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/7z9;->enableCheckAudioError:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableEvictCacheOnExoplayerErrors:Z

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->maxRetryCountByEvictCacheOnExoplayerErrors:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->disableAudioRendererOnAudioTrackInitFailed:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->audioTrackInitFailedFallbackApplyThreshold:I

    const-wide/32 v0, 0x493e0

    iput-wide v0, p0, LX/7z9;->killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableKillVideoProcessForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/7z9;->enableKillVideoProcessForIllegalStateException:Z

    iput-boolean v0, p0, LX/7z9;->enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/7z9;->enableRebootDeviceErrorUIForCodecInitFailed:Z

    iput-boolean v0, p0, LX/7z9;->enableRebootDeviceErrorUIForIllegalStateException:Z

    iput-boolean v0, p0, LX/7z9;->useThreadSafeStandaloneClock:Z

    iput-boolean v0, p0, LX/7z9;->useMultiPeriodBufferCalculation:Z

    iput-boolean v0, p0, LX/7z9;->isVideoQplPipelineEnabled:Z

    iput-boolean v0, p0, LX/7z9;->disableIsCachedApi:Z

    iput-boolean v0, p0, LX/7z9;->enableLoadErrorHandlingPolicy:Z

    iput-boolean v0, p0, LX/7z9;->enableBlockListingResource:Z

    iput-boolean v0, p0, LX/7z9;->enable500R1FallbackLogging:Z

    iput-boolean v0, p0, LX/7z9;->checkManifestRepresentationFormatMismatch:Z

    iput-boolean v0, p0, LX/7z9;->checkLiveSourceUri:Z

    iput-object v2, p0, LX/7z9;->oneSemanticsOsParamValue:Ljava/lang/String;

    iput-boolean v0, p0, LX/7z9;->forceOneSemanticsHandling:Z

    iput v0, p0, LX/7z9;->forceOneSemanticsWaveHandling:I

    iput v0, p0, LX/7z9;->expBackoffInRetryBaseDelay:I

    iput-boolean v0, p0, LX/7z9;->shouldLoadBinaryDataFromManifest:Z

    iput-boolean v0, p0, LX/7z9;->enhanceParseException:Z

    iput-boolean v0, p0, LX/7z9;->smartGcEnabled:Z

    iput v0, p0, LX/7z9;->smartGcTimeout:I

    iput-boolean v0, p0, LX/7z9;->getPlaybackPrefFromPrefetchRequest:Z

    iput-boolean v0, p0, LX/7z9;->useShortKey:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->staleManifestThreshold:I

    iput v0, p0, LX/7z9;->staleManifestThresholdToShowInterruptUI:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->checkThumbnailCache:Z

    iput-boolean v0, p0, LX/7z9;->ignore404AfterStreamEnd:Z

    iput-boolean v0, p0, LX/7z9;->allowPredictiveAlignment:Z

    iput-boolean v0, p0, LX/7z9;->enableUnifiedGrootErrorHandling:Z

    iput v0, p0, LX/7z9;->minScoreThresholdForLL:I

    iput v0, p0, LX/7z9;->goodVsrScoreThreshold:I

    iput v0, p0, LX/7z9;->maxTrackJumpsAllowed:I

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->maxDistanceBetweenTracksMs:I

    iput v0, p0, LX/7z9;->maxPastOtherTrackDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableVideoDebugEventLogging:Z

    iput-boolean v0, p0, LX/7z9;->respectDroppedQualityFlag:Z

    iput-object v2, p0, LX/7z9;->ssAbrExperimentSetting:Ljava/lang/String;

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->ssAbrAlphaDecay:F

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->ssAbrNumSamplesAvg:I

    iput v0, p0, LX/7z9;->ssAbrMinSamples:I

    iput-boolean v0, p0, LX/7z9;->enableJumpTrackFallingBehind:Z

    iput-boolean v0, p0, LX/7z9;->enable404SegmentRemapping:Z

    iput-boolean v0, p0, LX/7z9;->enableOneSemanticsLoaderRetry:Z

    iput-boolean v0, p0, LX/7z9;->enable204SegmentRemapping:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7z9;->maxPredictedSegmentsToRemap:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->skipThumbnailCacheKey:Z

    iput-boolean v0, p0, LX/7z9;->enableCreateByteBufferFromABufferNullCheckHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableBusySignalToFramework:Z

    iput-boolean v0, p0, LX/7z9;->shouldWarmupAwareOfAppScrolling:Z

    iput-boolean v0, p0, LX/7z9;->shouldUseWarmupSlot:Z

    iput-boolean v0, p0, LX/7z9;->enableDelayWarmupRunning:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->delayWarmupRunningMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableWarmupProcessPeriodically:Z

    iput-boolean v0, p0, LX/7z9;->enableStopWarmupSchedulerEmpty:Z

    iput-boolean v0, p0, LX/7z9;->enableFillBufferHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableFreeNodeHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableOnMessageReceivedHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableSendCommandHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableOnOMXEmptyBufferDoneHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableFillFreeBufferCheckNodeHooks:Z

    iput-boolean v0, p0, LX/7z9;->enableFixRemovePlayerViewFromParent:Z

    iput-boolean v0, p0, LX/7z9;->latencyControllerBypassLimits:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/7z9;->targetBufferBytesFactor:F

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->enableOverrideBufferWatermark:Z

    iput-boolean v1, p0, LX/7z9;->enableOverrideEndPosition:Z

    iget-object v0, p1, LX/7Hj;->A0M:LX/7ys;

    iput-object v0, p0, LX/7z9;->loggerSDKConfig:LX/7ys;

    iput-boolean v1, p0, LX/7z9;->enableMp4MultiTrafBoxesFix:Z

    const/4 v0, 0x5

    iput v0, p0, LX/7z9;->chunkSourceRetryMaximum:I

    iget-object v0, p1, LX/7Hj;->A0T:Ljava/util/Map;

    iput-object v0, p0, LX/7z9;->liveLatencySettings:Ljava/util/Map;

    iput-boolean v1, p0, LX/7z9;->forceDisableULL:Z

    iput v1, p0, LX/7z9;->bufferDecreaseTimeMs:I

    iput v1, p0, LX/7z9;->scalingBufferErrorMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/7z9;->timeBetweenPIDSamplesMs:I

    iput v0, p0, LX/7z9;->adjustSpeedBottomThresholdMs:I

    const/16 v0, 0x32

    iput v0, p0, LX/7z9;->desiredBufferAcceptableErrorMs:I

    iput-boolean v1, p0, LX/7z9;->disableSpeedAdjustmentOnBadUserExperience:Z

    const/16 v0, 0x12c

    iput v0, p0, LX/7z9;->adjustSpeedTopThresholdMs:I

    iput-boolean v1, p0, LX/7z9;->enableRetryErrorLoggingInCancel:Z

    iput-boolean v1, p0, LX/7z9;->enableRetryOnConnection:Z

    iput-boolean v1, p0, LX/7z9;->enableLoaderRetryLoggingForManifest:Z

    iput-boolean v1, p0, LX/7z9;->enableLoaderRetryLoggingForMedia:Z

    iput-boolean v1, p0, LX/7z9;->enableContinueLoadingLoggingForManifest:Z

    iput-boolean v1, p0, LX/7z9;->enableContinueLoadingLoggingForMedia:Z

    iput-boolean v1, p0, LX/7z9;->disableLoadingRetryOnFatalError:Z

    const/4 v0, 0x1

    iput v0, p0, LX/7z9;->errorRecoveryAttemptRepeatCountFlushThreshold:I

    iput-boolean v1, p0, LX/7z9;->disableNetworkErrorCountInChunkSource:Z

    iput-boolean v1, p0, LX/7z9;->ignoreEmptyProfileLevels:Z

    iput-boolean v1, p0, LX/7z9;->exceedRendererCapabilitiesIfAllFilteredOut:Z

    iput-boolean v1, p0, LX/7z9;->alwaysPrefetchInBgDefaultPriorityThread:Z

    iput-boolean v1, p0, LX/7z9;->alwaysPrefetchInIdleExecutor:Z

    iput-boolean v1, p0, LX/7z9;->enableCustomizedPrefetchThreadPriority:Z

    iput v1, p0, LX/7z9;->customizedPrefetchThreadPriority:I

    iput-boolean v0, p0, LX/7z9;->postStoriesGrootPrefetchToHeroManagerThread:Z

    iput-boolean v0, p0, LX/7z9;->cleanUpHeartbeatMessagesIfNotPlaying:Z

    iput-boolean v0, p0, LX/7z9;->cleanUpHeartbeatMessagesOnStall:Z

    iput-boolean v0, p0, LX/7z9;->cleanUpHeartbeatMessagesOnPause:Z

    iget-boolean v0, p1, LX/7Hj;->A0b:Z

    iput-boolean v0, p0, LX/7z9;->enableDynamicMinRebufferMsController:Z

    iput-boolean v1, p0, LX/7z9;->enableGlobalStallMonitor:Z

    iput-boolean v1, p0, LX/7z9;->enableGlobalNetworkMonitor:Z

    iput-boolean v1, p0, LX/7z9;->enableLiveTierSpecificBufferSetting:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->liveMinRetryCounts:I

    const/4 v0, 0x5

    iput v0, p0, LX/7z9;->prefetchThreadUpdatedPriority:I

    iput-boolean v1, p0, LX/7z9;->changeThreadPriorityForPrefetch:Z

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->numOfBytesBeforeLoaderThreadSleep:I

    iput-boolean v1, p0, LX/7z9;->enableLiveBroadcastErrorUI:Z

    iput-boolean v1, p0, LX/7z9;->enableFixTrackIndexOOB:Z

    iput-boolean v1, p0, LX/7z9;->shouldAlwaysDo503Retry:Z

    iput v0, p0, LX/7z9;->retryCountsForStartPlayManifestFetch:I

    iput v0, p0, LX/7z9;->retryCountsForStartPlayManifest503:I

    iput-boolean v1, p0, LX/7z9;->enableHttpPriorityForPrefetch:Z

    iput-boolean v1, p0, LX/7z9;->enableHttpPriorityForStreaming:Z

    iput-boolean v1, p0, LX/7z9;->useHttpPriorityIncrementalForStreaming:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->useHttpPriorityIncrementalForPrefetch:Z

    iput-boolean v0, p0, LX/7z9;->useHttpPriorityIncrementalForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/7z9;->useHttpPriorityWarmupForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/7z9;->useNetworkAwareHttpPriorityIncrementalForStreaming:Z

    iput-boolean v1, p0, LX/7z9;->useLowPriorityForSecondPhasePrefetch:Z

    iput v1, p0, LX/7z9;->bufferedDurationBasedHttpPriorityUpperBoundMs:I

    iput v1, p0, LX/7z9;->bufferedDurationBasedHttpPriorityLowerBoundMs:I

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/7z9;->watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

    iput-boolean v1, p0, LX/7z9;->changePriorityForPrefetchRequestOnPlayerStart:Z

    iput-boolean v1, p0, LX/7z9;->useLowerHttpPriorityForUnimportantPrefetch:Z

    iput-boolean v1, p0, LX/7z9;->useLowerHttpPriorityForAllPrefetch:Z

    iput-boolean v1, p0, LX/7z9;->useOutputSurfaceWorkaround:Z

    iput-boolean v1, p0, LX/7z9;->enableBufferAwareJumpSeek:Z

    iput v1, p0, LX/7z9;->jumpSeekPosLeftoverBufferDurationMs:I

    iput v1, p0, LX/7z9;->jumpSeekReductionFactorPct:I

    iput-boolean v1, p0, LX/7z9;->enableBackwardJumpSeekKeyframeSync:Z

    iput v1, p0, LX/7z9;->seekParameterOptionIndex:I

    iput-boolean v1, p0, LX/7z9;->skipAV1PreviousKeyFrameSeek:Z

    iput-boolean v1, p0, LX/7z9;->enableCacheLookUp:Z

    iput-boolean v1, p0, LX/7z9;->usePerVideoLookupToCheckCache:Z

    iput-boolean v1, p0, LX/7z9;->useIsCachedSkipInit:Z

    iput-boolean v1, p0, LX/7z9;->releaseHeroManagerWhenLowMemInBg:Z

    iput-boolean v1, p0, LX/7z9;->useAdAwareLoadControl:Z

    const v0, 0x3e99999a    # 0.3f

    iput v0, p0, LX/7z9;->huddleLatencyMaxSpeedDelta:F

    iput-boolean v1, p0, LX/7z9;->enablePIDForHuddle:Z

    iput-boolean v1, p0, LX/7z9;->forceStereoToMonoConversion:Z

    iput-boolean v1, p0, LX/7z9;->enableQuickDashPlayback:Z

    iput-boolean v1, p0, LX/7z9;->enableClockSync:Z

    iput-boolean v1, p0, LX/7z9;->enableStreamLatencyToggleOverride:Z

    iput v1, p0, LX/7z9;->streamLatencyToggleStateOverride:I

    const/16 v0, 0xbb8

    iput v0, p0, LX/7z9;->streamLatencyTogglePIDDesiredBufferMs:I

    const v0, 0x1d4c0

    iput v0, p0, LX/7z9;->streamLatencyTogglePIDIntegralBoundMs:I

    const v0, 0x3e99999a    # 0.3f

    iput v0, p0, LX/7z9;->streamLatencyToggleMaxSpeedDelta:F

    const/high16 v0, 0x40000000    # 2.0f

    iput v0, p0, LX/7z9;->streamLatencyToggleSpeedUpBandwidthMultiplier:F

    iput-boolean v1, p0, LX/7z9;->includePlaybackSessionIdHeader:Z

    iput-boolean v1, p0, LX/7z9;->enableE2ECDNTracing:Z

    iput-boolean v1, p0, LX/7z9;->enablePredictedUrlTracing:Z

    iput-object v2, p0, LX/7z9;->broadcasterIdAllowlist:Ljava/lang/String;

    iput-object v2, p0, LX/7z9;->playerOriginPausedLoadingBlackList:Ljava/lang/String;

    iget-object v0, p1, LX/7Hj;->A0V:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->pausedLoadingTriggerTypes:Ljava/util/Set;

    iget-object v0, p1, LX/7Hj;->A0U:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->originAllowlistForAlternateCodec:Ljava/util/Set;

    iget-object v0, p1, LX/7Hj;->A0Z:Ljava/util/Set;

    iput-object v0, p0, LX/7z9;->wakelockOriginLists:Ljava/util/Set;

    iput-boolean v1, p0, LX/7z9;->enableExcessiveNumUriRedirectLogging:Z

    iput v1, p0, LX/7z9;->excessiveUriRedirectLoggingLimit:I

    iput-boolean v1, p0, LX/7z9;->enableVodPausedLoading:Z

    iput v1, p0, LX/7z9;->maxBufferToDownloadInPausedLoadingMs:I

    iput v1, p0, LX/7z9;->maxTimeAllowedSpentInPausedLoadingMs:I

    iput-boolean v1, p0, LX/7z9;->enableLastPlaybackSpeedCacheUpdate:Z

    iput-boolean v1, p0, LX/7z9;->enableIsTextAdaptationSetNotFoundLogging:Z

    iput-boolean v1, p0, LX/7z9;->enableOffloadInitHeroService:Z

    iput-boolean v1, p0, LX/7z9;->enableBackgroundServicePlayerReuse:Z

    iput-boolean v1, p0, LX/7z9;->useMinIntentBasedWatermarkBeforePlay:Z

    iput-boolean v1, p0, LX/7z9;->enableMediaSessionControls:Z

    iput-boolean v1, p0, LX/7z9;->enableRequestAnalyticsTagsHeaderLogging:Z

    iput-boolean v1, p0, LX/7z9;->disableTextRendererOn404LoadError:Z

    iput-boolean v1, p0, LX/7z9;->useFallbackLogging:Z

    iput-boolean v1, p0, LX/7z9;->disableTextRendererOn404InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/7z9;->disableTextRendererOn500LoadError:Z

    iput-boolean v1, p0, LX/7z9;->disableTextRendererOn500InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/7z9;->enableVideoPlayerServerSideBweAnnotations:Z

    iput-boolean v1, p0, LX/7z9;->enableUnexpectedExoExceptionLogging:Z

    iput-boolean v1, p0, LX/7z9;->enableEmsgTrackForAll:Z

    iput-boolean v1, p0, LX/7z9;->enableInstreamAdsEmsgLog:Z

    iput v1, p0, LX/7z9;->audioStallCountThresholdMs:I

    iput-boolean v1, p0, LX/7z9;->enableVideoPositionLoggingInCompleteEvent:Z

    iput-boolean v1, p0, LX/7z9;->surfaceMPDFailoverImmediately:Z

    iput-boolean v1, p0, LX/7z9;->disableTextTrackOnMissingTextTrack:Z

    iput-boolean v1, p0, LX/7z9;->enableTextTrackWithKnownLanguage:Z

    iput v1, p0, LX/7z9;->numDashChunkMemoryCacheSampleStreams:I

    iput-boolean v1, p0, LX/7z9;->disableTextEraLoggingOnLoadRetry:Z

    iget-object v0, p1, LX/7Hj;->A0N:LX/7yn;

    iput-object v0, p0, LX/7z9;->tslogSettings:LX/7yn;

    iput-boolean v1, p0, LX/7z9;->dontRetry403OnExpiredUrl:Z

    iput-boolean v1, p0, LX/7z9;->useFullscreenTransitionPrediction:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/7z9;->fullscreenPredictionRequestTimeoutMs:J

    const/4 v0, -0x1

    iput v0, p0, LX/7z9;->maxAllowed503RetryCount:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->advanceSegmentOnNetworkErrors:J

    iput-wide v0, p0, LX/7z9;->maxSegmentsToAdvance:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableExplicitTextDataSourceCreation:Z

    iput-boolean v0, p0, LX/7z9;->disableLiveCaptioningOnPlayerInit:Z

    iput-boolean v0, p0, LX/7z9;->enableVrlQplLoggingEvents:Z

    iput-boolean v0, p0, LX/7z9;->reduceMemoryDataSinkMemorySpike:Z

    iput-boolean v0, p0, LX/7z9;->useExoPlayerBuilder:Z

    iput-boolean v0, p0, LX/7z9;->exoPlayerUpgrade218verifyApplicationThread:Z

    iput-boolean v0, p0, LX/7z9;->enable416Logging:Z

    iput-boolean v0, p0, LX/7z9;->enableVodContentLengthLogging:Z

    iput-boolean v0, p0, LX/7z9;->enableServerSideForwardTracing:Z

    iput-boolean v0, p0, LX/7z9;->enableMixedCodecManifestSupport:Z

    iput-boolean v0, p0, LX/7z9;->respectAbrForUll:Z

    iput-boolean v0, p0, LX/7z9;->respectAbrIndexForUll:Z

    iput-boolean v0, p0, LX/7z9;->disableUllBasedOnHoldout:Z

    iput-boolean v0, p0, LX/7z9;->enableWifiLockManager:Z

    iput-boolean v0, p0, LX/7z9;->enableClearStallOnBroadcastEnd:Z

    iput-boolean v0, p0, LX/7z9;->enableSecondaryChannelLoggingForLite:Z

    iput-boolean v0, p0, LX/7z9;->enableDav1dAsMediaCodecAdapter:Z

    iput-boolean v0, p0, LX/7z9;->enableDav1dOpenGLRendering:Z

    iput v0, p0, LX/7z9;->secondaryChannelLoggingMaxNumOfFramesInOneJson:I

    iput v0, p0, LX/7z9;->secondaryChannelLoggingMaxDisplayedFramesStringSize:I

    iput v0, p0, LX/7z9;->secondaryChannelLoggingSamplingFactor:I

    iput-boolean v0, p0, LX/7z9;->surfaceControlForceVideoSizeUpdate:Z

    iput-boolean v0, p0, LX/7z9;->forceAdjustSurfaceOnMainThread:Z

    iput-boolean v0, p0, LX/7z9;->disableVideoTrackForInVisibleVDD:Z

    iput-boolean v0, p0, LX/7z9;->shouldDisableAV1VideoTrackOnlyforVDD:Z

    iput-boolean v0, p0, LX/7z9;->useInterruptedIoException:Z

    iput-boolean v0, p0, LX/7z9;->enableMixeCodecManifestLogging:Z

    iput-boolean v0, p0, LX/7z9;->enableMixeCodecManifestVideoCodecSwitchedLogging:Z

    iput-boolean v0, p0, LX/7z9;->enablePCMBufferListener:Z

    iput-boolean v0, p0, LX/7z9;->enableLoggingEmptyOrNullVideoId:Z

    iput-boolean v0, p0, LX/7z9;->enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

    iput-boolean v0, p0, LX/7z9;->useBufferedCacheDataSink:Z

    iput-boolean v0, p0, LX/7z9;->useHandlerThreadPool:Z

    iget-boolean v0, p1, LX/7Hj;->A0h:Z

    iput-boolean v0, p0, LX/7z9;->useMainThreadForHeroPlayer:Z

    const/4 v0, 0x4

    iput v0, p0, LX/7z9;->handlerThreadPoolSize:I

    const/4 v0, 0x0

    iput v0, p0, LX/7z9;->bufferedCacheDataSinkSize:I

    iput-boolean v0, p0, LX/7z9;->enableAV1SRShader:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/7z9;->maxWidthForAV1SRShader:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableSaturation:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/7z9;->saturationFactor:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableAdditionalDecoderInitFailureMessage:Z

    iput-boolean v0, p0, LX/7z9;->enableFixForOnPreparingCallback:Z

    iput-boolean v0, p0, LX/7z9;->enableOpenGLSurfaceSizeUpdateFix:Z

    iput-object v2, p0, LX/7z9;->prefetchSubOriginBlockList:Ljava/lang/String;

    iput-boolean v0, p0, LX/7z9;->enforceSizeLimitOnSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/7z9;->attachGrootPlayerListenerWhenUsingSurfaceControl:Z

    iput-boolean v0, p0, LX/7z9;->resizeAndRepositionGrootSurfaceControl:Z

    iput-boolean v0, p0, LX/7z9;->preventAdjustWhenSurfaceNotValid:Z

    iput v0, p0, LX/7z9;->forceManifestFilteringMode:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->enableDav1dOpenGLRenderingHandleAspectRatio:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableMpdFilteringUtils:Z

    iput-boolean v0, p0, LX/7z9;->enableTransferListenerCallbackPerfFix:Z

    iput-boolean v0, p0, LX/7z9;->enableDynamicPrefetchCacheFileSize:Z

    iput-boolean v0, p0, LX/7z9;->enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/7z9;->minCacheFileSizeForDynamicChunkingInBytes:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/7z9;->enableDashManifestPool:Z

    iput v0, p0, LX/7z9;->dashManifestPoolSize:I

    iput-boolean v0, p0, LX/7z9;->disablePoolingForDav1dMediaCodec:Z

    iput-boolean v0, p0, LX/7z9;->useBackgroundHandlerForHeroLiveManager:Z

    iput-boolean v0, p0, LX/7z9;->useAllSettingsToSupportLowerLatency:Z

    iput-boolean v0, p0, LX/7z9;->combineInitFirstSegment:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/7z9;->fixNullCacheSpan:Z

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7z9;->enableAudioTrackRetry:Z

    iput v1, p0, LX/7z9;->playbackAboutToFinishCallbackTriggeringRemainingDuration:I

    iget-boolean v0, p1, LX/7Hj;->A0e:Z

    iput-boolean v0, p0, LX/7z9;->shouldAddDefaultMP4Extractor:Z

    iget-boolean v0, p1, LX/7Hj;->A0d:Z

    iput-boolean v0, p0, LX/7z9;->quitHandlerSafely:Z

    iget-boolean v0, p1, LX/7Hj;->A0f:Z

    iput-boolean v0, p0, LX/7z9;->shouldCleanupHeroManagerThread:Z

    iput-boolean v1, p0, LX/7z9;->enableCodecHistoryOverlayField:Z

    iput-boolean v1, p0, LX/7z9;->appendReconfigurationDataForDrmContentFix:Z

    iget v0, p1, LX/7Hj;->A09:I

    iput v0, p0, LX/7z9;->sdkVersionToUseDefaultLoadControl:I

    iget v0, p1, LX/7Hj;->A08:I

    iput v0, p0, LX/7z9;->sdkVersionToUseConservativeLoadControl:I

    iget v0, p1, LX/7Hj;->A07:I

    iput v0, p0, LX/7z9;->sdKVersionToUseCustomizedBuffering:I

    iget v0, p1, LX/7Hj;->A06:I

    iput v0, p0, LX/7z9;->minCustomizedWABufferMs:I

    iget v0, p1, LX/7Hj;->A05:I

    iput v0, p0, LX/7z9;->maxCustomizedWABufferMs:I

    iget v0, p1, LX/7Hj;->A00:I

    iput v0, p0, LX/7z9;->customizedWABufferForPlaybackMs:I

    iget v0, p1, LX/7Hj;->A02:I

    iput v0, p0, LX/7z9;->customizedWARebufferMs:I

    iget v0, p1, LX/7Hj;->A01:I

    iput v0, p0, LX/7z9;->customizedWAIndividualAllocationSize:I

    return-void
.end method
